// Code generated by protoc-gen-go. DO NOT EDIT.
// source: area_coverage.proto

package localservices

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VendorSubprovinceCoverage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AllSubprovinceId     int64    `protobuf:"varint,2,opt,name=all_subprovince_id,json=allSubprovinceId,proto3" json:"all_subprovince_id,omitempty"`
	VendorId             int64    `protobuf:"varint,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VendorSubprovinceCoverage) Reset()         { *m = VendorSubprovinceCoverage{} }
func (m *VendorSubprovinceCoverage) String() string { return proto.CompactTextString(m) }
func (*VendorSubprovinceCoverage) ProtoMessage()    {}
func (*VendorSubprovinceCoverage) Descriptor() ([]byte, []int) {
	return fileDescriptor_area_coverage_2565e926e7efc8cf, []int{0}
}
func (m *VendorSubprovinceCoverage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VendorSubprovinceCoverage.Unmarshal(m, b)
}
func (m *VendorSubprovinceCoverage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VendorSubprovinceCoverage.Marshal(b, m, deterministic)
}
func (dst *VendorSubprovinceCoverage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VendorSubprovinceCoverage.Merge(dst, src)
}
func (m *VendorSubprovinceCoverage) XXX_Size() int {
	return xxx_messageInfo_VendorSubprovinceCoverage.Size(m)
}
func (m *VendorSubprovinceCoverage) XXX_DiscardUnknown() {
	xxx_messageInfo_VendorSubprovinceCoverage.DiscardUnknown(m)
}

var xxx_messageInfo_VendorSubprovinceCoverage proto.InternalMessageInfo

func (m *VendorSubprovinceCoverage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VendorSubprovinceCoverage) GetAllSubprovinceId() int64 {
	if m != nil {
		return m.AllSubprovinceId
	}
	return 0
}

func (m *VendorSubprovinceCoverage) GetVendorId() int64 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

type CreateVendorSubprovinceCoverageRequest struct {
	VendorSubprovinceCoverage *VendorSubprovinceCoverage `protobuf:"bytes,1,opt,name=vendor_subprovince_coverage,json=vendorSubprovinceCoverage,proto3" json:"vendor_subprovince_coverage,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                   `json:"-"`
	XXX_unrecognized          []byte                     `json:"-"`
	XXX_sizecache             int32                      `json:"-"`
}

func (m *CreateVendorSubprovinceCoverageRequest) Reset() {
	*m = CreateVendorSubprovinceCoverageRequest{}
}
func (m *CreateVendorSubprovinceCoverageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVendorSubprovinceCoverageRequest) ProtoMessage()    {}
func (*CreateVendorSubprovinceCoverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_area_coverage_2565e926e7efc8cf, []int{1}
}
func (m *CreateVendorSubprovinceCoverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVendorSubprovinceCoverageRequest.Unmarshal(m, b)
}
func (m *CreateVendorSubprovinceCoverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVendorSubprovinceCoverageRequest.Marshal(b, m, deterministic)
}
func (dst *CreateVendorSubprovinceCoverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVendorSubprovinceCoverageRequest.Merge(dst, src)
}
func (m *CreateVendorSubprovinceCoverageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVendorSubprovinceCoverageRequest.Size(m)
}
func (m *CreateVendorSubprovinceCoverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVendorSubprovinceCoverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVendorSubprovinceCoverageRequest proto.InternalMessageInfo

func (m *CreateVendorSubprovinceCoverageRequest) GetVendorSubprovinceCoverage() *VendorSubprovinceCoverage {
	if m != nil {
		return m.VendorSubprovinceCoverage
	}
	return nil
}

type CreateVendorSubprovinceCoverageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVendorSubprovinceCoverageResponse) Reset() {
	*m = CreateVendorSubprovinceCoverageResponse{}
}
func (m *CreateVendorSubprovinceCoverageResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVendorSubprovinceCoverageResponse) ProtoMessage()    {}
func (*CreateVendorSubprovinceCoverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_area_coverage_2565e926e7efc8cf, []int{2}
}
func (m *CreateVendorSubprovinceCoverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVendorSubprovinceCoverageResponse.Unmarshal(m, b)
}
func (m *CreateVendorSubprovinceCoverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVendorSubprovinceCoverageResponse.Marshal(b, m, deterministic)
}
func (dst *CreateVendorSubprovinceCoverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVendorSubprovinceCoverageResponse.Merge(dst, src)
}
func (m *CreateVendorSubprovinceCoverageResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVendorSubprovinceCoverageResponse.Size(m)
}
func (m *CreateVendorSubprovinceCoverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVendorSubprovinceCoverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVendorSubprovinceCoverageResponse proto.InternalMessageInfo

type GetVendorSubprovinceCoveragesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVendorSubprovinceCoveragesRequest) Reset()         { *m = GetVendorSubprovinceCoveragesRequest{} }
func (m *GetVendorSubprovinceCoveragesRequest) String() string { return proto.CompactTextString(m) }
func (*GetVendorSubprovinceCoveragesRequest) ProtoMessage()    {}
func (*GetVendorSubprovinceCoveragesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_area_coverage_2565e926e7efc8cf, []int{3}
}
func (m *GetVendorSubprovinceCoveragesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVendorSubprovinceCoveragesRequest.Unmarshal(m, b)
}
func (m *GetVendorSubprovinceCoveragesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVendorSubprovinceCoveragesRequest.Marshal(b, m, deterministic)
}
func (dst *GetVendorSubprovinceCoveragesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVendorSubprovinceCoveragesRequest.Merge(dst, src)
}
func (m *GetVendorSubprovinceCoveragesRequest) XXX_Size() int {
	return xxx_messageInfo_GetVendorSubprovinceCoveragesRequest.Size(m)
}
func (m *GetVendorSubprovinceCoveragesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVendorSubprovinceCoveragesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVendorSubprovinceCoveragesRequest proto.InternalMessageInfo

type GetVendorSubprovinceCoveragesResponse struct {
	VendorSubprovinceCoverage []*VendorSubprovinceCoverage `protobuf:"bytes,1,rep,name=vendor_subprovince_coverage,json=vendorSubprovinceCoverage,proto3" json:"vendor_subprovince_coverage,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                     `json:"-"`
	XXX_unrecognized          []byte                       `json:"-"`
	XXX_sizecache             int32                        `json:"-"`
}

func (m *GetVendorSubprovinceCoveragesResponse) Reset()         { *m = GetVendorSubprovinceCoveragesResponse{} }
func (m *GetVendorSubprovinceCoveragesResponse) String() string { return proto.CompactTextString(m) }
func (*GetVendorSubprovinceCoveragesResponse) ProtoMessage()    {}
func (*GetVendorSubprovinceCoveragesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_area_coverage_2565e926e7efc8cf, []int{4}
}
func (m *GetVendorSubprovinceCoveragesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVendorSubprovinceCoveragesResponse.Unmarshal(m, b)
}
func (m *GetVendorSubprovinceCoveragesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVendorSubprovinceCoveragesResponse.Marshal(b, m, deterministic)
}
func (dst *GetVendorSubprovinceCoveragesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVendorSubprovinceCoveragesResponse.Merge(dst, src)
}
func (m *GetVendorSubprovinceCoveragesResponse) XXX_Size() int {
	return xxx_messageInfo_GetVendorSubprovinceCoveragesResponse.Size(m)
}
func (m *GetVendorSubprovinceCoveragesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVendorSubprovinceCoveragesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVendorSubprovinceCoveragesResponse proto.InternalMessageInfo

func (m *GetVendorSubprovinceCoveragesResponse) GetVendorSubprovinceCoverage() []*VendorSubprovinceCoverage {
	if m != nil {
		return m.VendorSubprovinceCoverage
	}
	return nil
}

type GetVendorSubprovinceCoverageByIdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVendorSubprovinceCoverageByIdRequest) Reset() {
	*m = GetVendorSubprovinceCoverageByIdRequest{}
}
func (m *GetVendorSubprovinceCoverageByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetVendorSubprovinceCoverageByIdRequest) ProtoMessage()    {}
func (*GetVendorSubprovinceCoverageByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_area_coverage_2565e926e7efc8cf, []int{5}
}
func (m *GetVendorSubprovinceCoverageByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVendorSubprovinceCoverageByIdRequest.Unmarshal(m, b)
}
func (m *GetVendorSubprovinceCoverageByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVendorSubprovinceCoverageByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetVendorSubprovinceCoverageByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVendorSubprovinceCoverageByIdRequest.Merge(dst, src)
}
func (m *GetVendorSubprovinceCoverageByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetVendorSubprovinceCoverageByIdRequest.Size(m)
}
func (m *GetVendorSubprovinceCoverageByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVendorSubprovinceCoverageByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVendorSubprovinceCoverageByIdRequest proto.InternalMessageInfo

func (m *GetVendorSubprovinceCoverageByIdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetVendorSubprovinceCoverageByIdResponse struct {
	VendorSubprovinceCoverage *VendorSubprovinceCoverage `protobuf:"bytes,1,opt,name=vendor_subprovince_coverage,json=vendorSubprovinceCoverage,proto3" json:"vendor_subprovince_coverage,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                   `json:"-"`
	XXX_unrecognized          []byte                     `json:"-"`
	XXX_sizecache             int32                      `json:"-"`
}

func (m *GetVendorSubprovinceCoverageByIdResponse) Reset() {
	*m = GetVendorSubprovinceCoverageByIdResponse{}
}
func (m *GetVendorSubprovinceCoverageByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetVendorSubprovinceCoverageByIdResponse) ProtoMessage()    {}
func (*GetVendorSubprovinceCoverageByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_area_coverage_2565e926e7efc8cf, []int{6}
}
func (m *GetVendorSubprovinceCoverageByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVendorSubprovinceCoverageByIdResponse.Unmarshal(m, b)
}
func (m *GetVendorSubprovinceCoverageByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVendorSubprovinceCoverageByIdResponse.Marshal(b, m, deterministic)
}
func (dst *GetVendorSubprovinceCoverageByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVendorSubprovinceCoverageByIdResponse.Merge(dst, src)
}
func (m *GetVendorSubprovinceCoverageByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetVendorSubprovinceCoverageByIdResponse.Size(m)
}
func (m *GetVendorSubprovinceCoverageByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVendorSubprovinceCoverageByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVendorSubprovinceCoverageByIdResponse proto.InternalMessageInfo

func (m *GetVendorSubprovinceCoverageByIdResponse) GetVendorSubprovinceCoverage() *VendorSubprovinceCoverage {
	if m != nil {
		return m.VendorSubprovinceCoverage
	}
	return nil
}

type UpdateVendorSubprovinceCoverageRequest struct {
	VendorSubprovinceCoverage *VendorSubprovinceCoverage `protobuf:"bytes,1,opt,name=vendor_subprovince_coverage,json=vendorSubprovinceCoverage,proto3" json:"vendor_subprovince_coverage,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                   `json:"-"`
	XXX_unrecognized          []byte                     `json:"-"`
	XXX_sizecache             int32                      `json:"-"`
}

func (m *UpdateVendorSubprovinceCoverageRequest) Reset() {
	*m = UpdateVendorSubprovinceCoverageRequest{}
}
func (m *UpdateVendorSubprovinceCoverageRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateVendorSubprovinceCoverageRequest) ProtoMessage()    {}
func (*UpdateVendorSubprovinceCoverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_area_coverage_2565e926e7efc8cf, []int{7}
}
func (m *UpdateVendorSubprovinceCoverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVendorSubprovinceCoverageRequest.Unmarshal(m, b)
}
func (m *UpdateVendorSubprovinceCoverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVendorSubprovinceCoverageRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateVendorSubprovinceCoverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVendorSubprovinceCoverageRequest.Merge(dst, src)
}
func (m *UpdateVendorSubprovinceCoverageRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateVendorSubprovinceCoverageRequest.Size(m)
}
func (m *UpdateVendorSubprovinceCoverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVendorSubprovinceCoverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVendorSubprovinceCoverageRequest proto.InternalMessageInfo

func (m *UpdateVendorSubprovinceCoverageRequest) GetVendorSubprovinceCoverage() *VendorSubprovinceCoverage {
	if m != nil {
		return m.VendorSubprovinceCoverage
	}
	return nil
}

type UpdateVendorSubprovinceCoverageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateVendorSubprovinceCoverageResponse) Reset() {
	*m = UpdateVendorSubprovinceCoverageResponse{}
}
func (m *UpdateVendorSubprovinceCoverageResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateVendorSubprovinceCoverageResponse) ProtoMessage()    {}
func (*UpdateVendorSubprovinceCoverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_area_coverage_2565e926e7efc8cf, []int{8}
}
func (m *UpdateVendorSubprovinceCoverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVendorSubprovinceCoverageResponse.Unmarshal(m, b)
}
func (m *UpdateVendorSubprovinceCoverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVendorSubprovinceCoverageResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateVendorSubprovinceCoverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVendorSubprovinceCoverageResponse.Merge(dst, src)
}
func (m *UpdateVendorSubprovinceCoverageResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateVendorSubprovinceCoverageResponse.Size(m)
}
func (m *UpdateVendorSubprovinceCoverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVendorSubprovinceCoverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVendorSubprovinceCoverageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VendorSubprovinceCoverage)(nil), "VendorSubprovinceCoverage")
	proto.RegisterType((*CreateVendorSubprovinceCoverageRequest)(nil), "CreateVendorSubprovinceCoverageRequest")
	proto.RegisterType((*CreateVendorSubprovinceCoverageResponse)(nil), "CreateVendorSubprovinceCoverageResponse")
	proto.RegisterType((*GetVendorSubprovinceCoveragesRequest)(nil), "GetVendorSubprovinceCoveragesRequest")
	proto.RegisterType((*GetVendorSubprovinceCoveragesResponse)(nil), "GetVendorSubprovinceCoveragesResponse")
	proto.RegisterType((*GetVendorSubprovinceCoverageByIdRequest)(nil), "GetVendorSubprovinceCoverageByIdRequest")
	proto.RegisterType((*GetVendorSubprovinceCoverageByIdResponse)(nil), "GetVendorSubprovinceCoverageByIdResponse")
	proto.RegisterType((*UpdateVendorSubprovinceCoverageRequest)(nil), "UpdateVendorSubprovinceCoverageRequest")
	proto.RegisterType((*UpdateVendorSubprovinceCoverageResponse)(nil), "UpdateVendorSubprovinceCoverageResponse")
}

func init() { proto.RegisterFile("area_coverage.proto", fileDescriptor_area_coverage_2565e926e7efc8cf) }

var fileDescriptor_area_coverage_2565e926e7efc8cf = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0x4a, 0x4d,
	0x8c, 0x4f, 0xce, 0x2f, 0x4b, 0x2d, 0x4a, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57,
	0x2a, 0xe3, 0x92, 0x0c, 0x4b, 0xcd, 0x4b, 0xc9, 0x2f, 0x0a, 0x2e, 0x4d, 0x2a, 0x28, 0xca, 0x2f,
	0xcb, 0xcc, 0x4b, 0x4e, 0x75, 0x86, 0x2a, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x11, 0xd2, 0xe1, 0x12, 0x4a, 0xcc, 0xc9, 0x89, 0x2f,
	0x46, 0x28, 0x8d, 0xcf, 0x4c, 0x91, 0x60, 0x02, 0xcb, 0x0b, 0x24, 0xe6, 0xe4, 0x20, 0x99, 0xe1,
	0x99, 0x22, 0x24, 0xcd, 0xc5, 0x59, 0x06, 0x36, 0x1a, 0xa4, 0x88, 0x19, 0xac, 0x88, 0x03, 0x22,
	0xe0, 0x99, 0xa2, 0xd4, 0xc2, 0xc8, 0xa5, 0xe6, 0x5c, 0x94, 0x9a, 0x58, 0x92, 0x8a, 0xd3, 0xfa,
	0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0xa1, 0x28, 0x2e, 0x69, 0xa8, 0x39, 0xc8, 0x16, 0xc3,
	0xfc, 0x01, 0x76, 0x1e, 0xb7, 0x91, 0x94, 0x1e, 0x6e, 0x73, 0x24, 0xcb, 0x70, 0x49, 0x29, 0x69,
	0x72, 0xa9, 0x13, 0x74, 0x45, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x92, 0x1a, 0x97, 0x8a, 0x7b,
	0x6a, 0x09, 0x4e, 0x75, 0xc5, 0x50, 0xe7, 0x2a, 0x35, 0x33, 0x72, 0xa9, 0x12, 0x50, 0x08, 0x31,
	0x91, 0xb0, 0xc7, 0x98, 0xc9, 0xf7, 0x98, 0x25, 0x97, 0x3a, 0x3e, 0x47, 0x38, 0x55, 0x7a, 0xa6,
	0xc0, 0xc2, 0x17, 0x2d, 0x96, 0x95, 0xda, 0x18, 0xb9, 0x34, 0x08, 0xeb, 0x25, 0xd6, 0x0f, 0x14,
	0x44, 0x0e, 0x28, 0x8d, 0x84, 0x16, 0xa4, 0x0c, 0x82, 0x34, 0x42, 0xd0, 0x15, 0x90, 0xd0, 0x70,
	0xe2, 0x8f, 0xe2, 0xcd, 0xc9, 0x4f, 0x4e, 0xcc, 0x29, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x2d,
	0x4e, 0x62, 0x03, 0xe7, 0x32, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0x30, 0x87, 0x33,
	0x7c, 0x03, 0x00, 0x00,
}
