// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product_spec_value.proto

package localservices

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProductSpecValue struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProductSpecSetId     int64    `protobuf:"varint,3,opt,name=product_spec_set_id,json=productSpecSetId,proto3" json:"product_spec_set_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductSpecValue) Reset()         { *m = ProductSpecValue{} }
func (m *ProductSpecValue) String() string { return proto.CompactTextString(m) }
func (*ProductSpecValue) ProtoMessage()    {}
func (*ProductSpecValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{0}
}
func (m *ProductSpecValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSpecValue.Unmarshal(m, b)
}
func (m *ProductSpecValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSpecValue.Marshal(b, m, deterministic)
}
func (dst *ProductSpecValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSpecValue.Merge(dst, src)
}
func (m *ProductSpecValue) XXX_Size() int {
	return xxx_messageInfo_ProductSpecValue.Size(m)
}
func (m *ProductSpecValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSpecValue.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSpecValue proto.InternalMessageInfo

func (m *ProductSpecValue) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductSpecValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductSpecValue) GetProductSpecSetId() int64 {
	if m != nil {
		return m.ProductSpecSetId
	}
	return 0
}

type CreateProductSpecValueRequest struct {
	SpecValue            *ProductSpecValue `protobuf:"bytes,1,opt,name=spec_value,json=specValue,proto3" json:"spec_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateProductSpecValueRequest) Reset()         { *m = CreateProductSpecValueRequest{} }
func (m *CreateProductSpecValueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductSpecValueRequest) ProtoMessage()    {}
func (*CreateProductSpecValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{1}
}
func (m *CreateProductSpecValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductSpecValueRequest.Unmarshal(m, b)
}
func (m *CreateProductSpecValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductSpecValueRequest.Marshal(b, m, deterministic)
}
func (dst *CreateProductSpecValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductSpecValueRequest.Merge(dst, src)
}
func (m *CreateProductSpecValueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductSpecValueRequest.Size(m)
}
func (m *CreateProductSpecValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductSpecValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductSpecValueRequest proto.InternalMessageInfo

func (m *CreateProductSpecValueRequest) GetSpecValue() *ProductSpecValue {
	if m != nil {
		return m.SpecValue
	}
	return nil
}

type CreateProductSpecValueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductSpecValueResponse) Reset()         { *m = CreateProductSpecValueResponse{} }
func (m *CreateProductSpecValueResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductSpecValueResponse) ProtoMessage()    {}
func (*CreateProductSpecValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{2}
}
func (m *CreateProductSpecValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductSpecValueResponse.Unmarshal(m, b)
}
func (m *CreateProductSpecValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductSpecValueResponse.Marshal(b, m, deterministic)
}
func (dst *CreateProductSpecValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductSpecValueResponse.Merge(dst, src)
}
func (m *CreateProductSpecValueResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductSpecValueResponse.Size(m)
}
func (m *CreateProductSpecValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductSpecValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductSpecValueResponse proto.InternalMessageInfo

type GetProductSpecValuesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductSpecValuesRequest) Reset()         { *m = GetProductSpecValuesRequest{} }
func (m *GetProductSpecValuesRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductSpecValuesRequest) ProtoMessage()    {}
func (*GetProductSpecValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{3}
}
func (m *GetProductSpecValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSpecValuesRequest.Unmarshal(m, b)
}
func (m *GetProductSpecValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSpecValuesRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductSpecValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSpecValuesRequest.Merge(dst, src)
}
func (m *GetProductSpecValuesRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductSpecValuesRequest.Size(m)
}
func (m *GetProductSpecValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSpecValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSpecValuesRequest proto.InternalMessageInfo

type GetProductSpecValuesResponse struct {
	SpecValue            []*ProductSpecValue `protobuf:"bytes,1,rep,name=spec_value,json=specValue,proto3" json:"spec_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetProductSpecValuesResponse) Reset()         { *m = GetProductSpecValuesResponse{} }
func (m *GetProductSpecValuesResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductSpecValuesResponse) ProtoMessage()    {}
func (*GetProductSpecValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{4}
}
func (m *GetProductSpecValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSpecValuesResponse.Unmarshal(m, b)
}
func (m *GetProductSpecValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSpecValuesResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductSpecValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSpecValuesResponse.Merge(dst, src)
}
func (m *GetProductSpecValuesResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductSpecValuesResponse.Size(m)
}
func (m *GetProductSpecValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSpecValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSpecValuesResponse proto.InternalMessageInfo

func (m *GetProductSpecValuesResponse) GetSpecValue() []*ProductSpecValue {
	if m != nil {
		return m.SpecValue
	}
	return nil
}

type GetProductSpecValueByIdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductSpecValueByIdRequest) Reset()         { *m = GetProductSpecValueByIdRequest{} }
func (m *GetProductSpecValueByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductSpecValueByIdRequest) ProtoMessage()    {}
func (*GetProductSpecValueByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{5}
}
func (m *GetProductSpecValueByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSpecValueByIdRequest.Unmarshal(m, b)
}
func (m *GetProductSpecValueByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSpecValueByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductSpecValueByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSpecValueByIdRequest.Merge(dst, src)
}
func (m *GetProductSpecValueByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductSpecValueByIdRequest.Size(m)
}
func (m *GetProductSpecValueByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSpecValueByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSpecValueByIdRequest proto.InternalMessageInfo

func (m *GetProductSpecValueByIdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetProductSpecValueByIdResponse struct {
	SpecValue            *ProductSpecValue `protobuf:"bytes,1,opt,name=spec_value,json=specValue,proto3" json:"spec_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetProductSpecValueByIdResponse) Reset()         { *m = GetProductSpecValueByIdResponse{} }
func (m *GetProductSpecValueByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductSpecValueByIdResponse) ProtoMessage()    {}
func (*GetProductSpecValueByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{6}
}
func (m *GetProductSpecValueByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSpecValueByIdResponse.Unmarshal(m, b)
}
func (m *GetProductSpecValueByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSpecValueByIdResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductSpecValueByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSpecValueByIdResponse.Merge(dst, src)
}
func (m *GetProductSpecValueByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductSpecValueByIdResponse.Size(m)
}
func (m *GetProductSpecValueByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSpecValueByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSpecValueByIdResponse proto.InternalMessageInfo

func (m *GetProductSpecValueByIdResponse) GetSpecValue() *ProductSpecValue {
	if m != nil {
		return m.SpecValue
	}
	return nil
}

type UpdateProductSpecValueRequest struct {
	SpecValue            *ProductSpecValue `protobuf:"bytes,1,opt,name=spec_value,json=specValue,proto3" json:"spec_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateProductSpecValueRequest) Reset()         { *m = UpdateProductSpecValueRequest{} }
func (m *UpdateProductSpecValueRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductSpecValueRequest) ProtoMessage()    {}
func (*UpdateProductSpecValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{7}
}
func (m *UpdateProductSpecValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductSpecValueRequest.Unmarshal(m, b)
}
func (m *UpdateProductSpecValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductSpecValueRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateProductSpecValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductSpecValueRequest.Merge(dst, src)
}
func (m *UpdateProductSpecValueRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductSpecValueRequest.Size(m)
}
func (m *UpdateProductSpecValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductSpecValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductSpecValueRequest proto.InternalMessageInfo

func (m *UpdateProductSpecValueRequest) GetSpecValue() *ProductSpecValue {
	if m != nil {
		return m.SpecValue
	}
	return nil
}

type UpdateProductSpecValueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductSpecValueResponse) Reset()         { *m = UpdateProductSpecValueResponse{} }
func (m *UpdateProductSpecValueResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductSpecValueResponse) ProtoMessage()    {}
func (*UpdateProductSpecValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{8}
}
func (m *UpdateProductSpecValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductSpecValueResponse.Unmarshal(m, b)
}
func (m *UpdateProductSpecValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductSpecValueResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateProductSpecValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductSpecValueResponse.Merge(dst, src)
}
func (m *UpdateProductSpecValueResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductSpecValueResponse.Size(m)
}
func (m *UpdateProductSpecValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductSpecValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductSpecValueResponse proto.InternalMessageInfo

type DeleteProductSpecValueRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductSpecValueRequest) Reset()         { *m = DeleteProductSpecValueRequest{} }
func (m *DeleteProductSpecValueRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductSpecValueRequest) ProtoMessage()    {}
func (*DeleteProductSpecValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{9}
}
func (m *DeleteProductSpecValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductSpecValueRequest.Unmarshal(m, b)
}
func (m *DeleteProductSpecValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductSpecValueRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteProductSpecValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductSpecValueRequest.Merge(dst, src)
}
func (m *DeleteProductSpecValueRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductSpecValueRequest.Size(m)
}
func (m *DeleteProductSpecValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductSpecValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductSpecValueRequest proto.InternalMessageInfo

func (m *DeleteProductSpecValueRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteProductSpecValueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductSpecValueResponse) Reset()         { *m = DeleteProductSpecValueResponse{} }
func (m *DeleteProductSpecValueResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProductSpecValueResponse) ProtoMessage()    {}
func (*DeleteProductSpecValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{10}
}
func (m *DeleteProductSpecValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductSpecValueResponse.Unmarshal(m, b)
}
func (m *DeleteProductSpecValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductSpecValueResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteProductSpecValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductSpecValueResponse.Merge(dst, src)
}
func (m *DeleteProductSpecValueResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProductSpecValueResponse.Size(m)
}
func (m *DeleteProductSpecValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductSpecValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductSpecValueResponse proto.InternalMessageInfo

type ProductSpecValueMap struct {
	Id                       int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VendorId                 int64    `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ProductSpecValueId       int64    `protobuf:"varint,3,opt,name=product_spec_value_id,json=productSpecValueId,proto3" json:"product_spec_value_id,omitempty"`
	ProductVendorSpecValueId int64    `protobuf:"varint,4,opt,name=product_vendor_spec_value_id,json=productVendorSpecValueId,proto3" json:"product_vendor_spec_value_id,omitempty"`
	VendorSpecValueId        int64    `protobuf:"varint,5,opt,name=vendor_spec_value_id,json=vendorSpecValueId,proto3" json:"vendor_spec_value_id,omitempty"`
	ProductId                int64    `protobuf:"varint,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *ProductSpecValueMap) Reset()         { *m = ProductSpecValueMap{} }
func (m *ProductSpecValueMap) String() string { return proto.CompactTextString(m) }
func (*ProductSpecValueMap) ProtoMessage()    {}
func (*ProductSpecValueMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{11}
}
func (m *ProductSpecValueMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSpecValueMap.Unmarshal(m, b)
}
func (m *ProductSpecValueMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSpecValueMap.Marshal(b, m, deterministic)
}
func (dst *ProductSpecValueMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSpecValueMap.Merge(dst, src)
}
func (m *ProductSpecValueMap) XXX_Size() int {
	return xxx_messageInfo_ProductSpecValueMap.Size(m)
}
func (m *ProductSpecValueMap) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSpecValueMap.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSpecValueMap proto.InternalMessageInfo

func (m *ProductSpecValueMap) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductSpecValueMap) GetVendorId() int64 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *ProductSpecValueMap) GetProductSpecValueId() int64 {
	if m != nil {
		return m.ProductSpecValueId
	}
	return 0
}

func (m *ProductSpecValueMap) GetProductVendorSpecValueId() int64 {
	if m != nil {
		return m.ProductVendorSpecValueId
	}
	return 0
}

func (m *ProductSpecValueMap) GetVendorSpecValueId() int64 {
	if m != nil {
		return m.VendorSpecValueId
	}
	return 0
}

func (m *ProductSpecValueMap) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type CreateProductSpecValueMapRequest struct {
	SpecValueMap         *ProductSpecValueMap `protobuf:"bytes,1,opt,name=spec_value_map,json=specValueMap,proto3" json:"spec_value_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateProductSpecValueMapRequest) Reset()         { *m = CreateProductSpecValueMapRequest{} }
func (m *CreateProductSpecValueMapRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductSpecValueMapRequest) ProtoMessage()    {}
func (*CreateProductSpecValueMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{12}
}
func (m *CreateProductSpecValueMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductSpecValueMapRequest.Unmarshal(m, b)
}
func (m *CreateProductSpecValueMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductSpecValueMapRequest.Marshal(b, m, deterministic)
}
func (dst *CreateProductSpecValueMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductSpecValueMapRequest.Merge(dst, src)
}
func (m *CreateProductSpecValueMapRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductSpecValueMapRequest.Size(m)
}
func (m *CreateProductSpecValueMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductSpecValueMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductSpecValueMapRequest proto.InternalMessageInfo

func (m *CreateProductSpecValueMapRequest) GetSpecValueMap() *ProductSpecValueMap {
	if m != nil {
		return m.SpecValueMap
	}
	return nil
}

type CreateProductSpecValueMapResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductSpecValueMapResponse) Reset()         { *m = CreateProductSpecValueMapResponse{} }
func (m *CreateProductSpecValueMapResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductSpecValueMapResponse) ProtoMessage()    {}
func (*CreateProductSpecValueMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{13}
}
func (m *CreateProductSpecValueMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductSpecValueMapResponse.Unmarshal(m, b)
}
func (m *CreateProductSpecValueMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductSpecValueMapResponse.Marshal(b, m, deterministic)
}
func (dst *CreateProductSpecValueMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductSpecValueMapResponse.Merge(dst, src)
}
func (m *CreateProductSpecValueMapResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductSpecValueMapResponse.Size(m)
}
func (m *CreateProductSpecValueMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductSpecValueMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductSpecValueMapResponse proto.InternalMessageInfo

type GetProductSpecValueMapsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductSpecValueMapsRequest) Reset()         { *m = GetProductSpecValueMapsRequest{} }
func (m *GetProductSpecValueMapsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductSpecValueMapsRequest) ProtoMessage()    {}
func (*GetProductSpecValueMapsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{14}
}
func (m *GetProductSpecValueMapsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSpecValueMapsRequest.Unmarshal(m, b)
}
func (m *GetProductSpecValueMapsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSpecValueMapsRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductSpecValueMapsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSpecValueMapsRequest.Merge(dst, src)
}
func (m *GetProductSpecValueMapsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductSpecValueMapsRequest.Size(m)
}
func (m *GetProductSpecValueMapsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSpecValueMapsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSpecValueMapsRequest proto.InternalMessageInfo

type GetProductSpecValueMapsResponse struct {
	SpecValueMap         []*ProductSpecValueMap `protobuf:"bytes,1,rep,name=spec_value_map,json=specValueMap,proto3" json:"spec_value_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetProductSpecValueMapsResponse) Reset()         { *m = GetProductSpecValueMapsResponse{} }
func (m *GetProductSpecValueMapsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductSpecValueMapsResponse) ProtoMessage()    {}
func (*GetProductSpecValueMapsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{15}
}
func (m *GetProductSpecValueMapsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSpecValueMapsResponse.Unmarshal(m, b)
}
func (m *GetProductSpecValueMapsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSpecValueMapsResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductSpecValueMapsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSpecValueMapsResponse.Merge(dst, src)
}
func (m *GetProductSpecValueMapsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductSpecValueMapsResponse.Size(m)
}
func (m *GetProductSpecValueMapsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSpecValueMapsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSpecValueMapsResponse proto.InternalMessageInfo

func (m *GetProductSpecValueMapsResponse) GetSpecValueMap() []*ProductSpecValueMap {
	if m != nil {
		return m.SpecValueMap
	}
	return nil
}

type GetProductSpecValueMapByIdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductSpecValueMapByIdRequest) Reset()         { *m = GetProductSpecValueMapByIdRequest{} }
func (m *GetProductSpecValueMapByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductSpecValueMapByIdRequest) ProtoMessage()    {}
func (*GetProductSpecValueMapByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{16}
}
func (m *GetProductSpecValueMapByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSpecValueMapByIdRequest.Unmarshal(m, b)
}
func (m *GetProductSpecValueMapByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSpecValueMapByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductSpecValueMapByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSpecValueMapByIdRequest.Merge(dst, src)
}
func (m *GetProductSpecValueMapByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductSpecValueMapByIdRequest.Size(m)
}
func (m *GetProductSpecValueMapByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSpecValueMapByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSpecValueMapByIdRequest proto.InternalMessageInfo

func (m *GetProductSpecValueMapByIdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetProductSpecValueMapByIdResponse struct {
	SpecValueMap         *ProductSpecValueMap `protobuf:"bytes,1,opt,name=spec_value_map,json=specValueMap,proto3" json:"spec_value_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetProductSpecValueMapByIdResponse) Reset()         { *m = GetProductSpecValueMapByIdResponse{} }
func (m *GetProductSpecValueMapByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductSpecValueMapByIdResponse) ProtoMessage()    {}
func (*GetProductSpecValueMapByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{17}
}
func (m *GetProductSpecValueMapByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSpecValueMapByIdResponse.Unmarshal(m, b)
}
func (m *GetProductSpecValueMapByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSpecValueMapByIdResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductSpecValueMapByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSpecValueMapByIdResponse.Merge(dst, src)
}
func (m *GetProductSpecValueMapByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductSpecValueMapByIdResponse.Size(m)
}
func (m *GetProductSpecValueMapByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSpecValueMapByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSpecValueMapByIdResponse proto.InternalMessageInfo

func (m *GetProductSpecValueMapByIdResponse) GetSpecValueMap() *ProductSpecValueMap {
	if m != nil {
		return m.SpecValueMap
	}
	return nil
}

type UpdateProductSpecValueMapRequest struct {
	SpecValueMap         *ProductSpecValueMap `protobuf:"bytes,1,opt,name=spec_value_map,json=specValueMap,proto3" json:"spec_value_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateProductSpecValueMapRequest) Reset()         { *m = UpdateProductSpecValueMapRequest{} }
func (m *UpdateProductSpecValueMapRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductSpecValueMapRequest) ProtoMessage()    {}
func (*UpdateProductSpecValueMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{18}
}
func (m *UpdateProductSpecValueMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductSpecValueMapRequest.Unmarshal(m, b)
}
func (m *UpdateProductSpecValueMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductSpecValueMapRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateProductSpecValueMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductSpecValueMapRequest.Merge(dst, src)
}
func (m *UpdateProductSpecValueMapRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductSpecValueMapRequest.Size(m)
}
func (m *UpdateProductSpecValueMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductSpecValueMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductSpecValueMapRequest proto.InternalMessageInfo

func (m *UpdateProductSpecValueMapRequest) GetSpecValueMap() *ProductSpecValueMap {
	if m != nil {
		return m.SpecValueMap
	}
	return nil
}

type UpdateProductSpecValueMapResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductSpecValueMapResponse) Reset()         { *m = UpdateProductSpecValueMapResponse{} }
func (m *UpdateProductSpecValueMapResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductSpecValueMapResponse) ProtoMessage()    {}
func (*UpdateProductSpecValueMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{19}
}
func (m *UpdateProductSpecValueMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductSpecValueMapResponse.Unmarshal(m, b)
}
func (m *UpdateProductSpecValueMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductSpecValueMapResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateProductSpecValueMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductSpecValueMapResponse.Merge(dst, src)
}
func (m *UpdateProductSpecValueMapResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductSpecValueMapResponse.Size(m)
}
func (m *UpdateProductSpecValueMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductSpecValueMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductSpecValueMapResponse proto.InternalMessageInfo

type DeleteProductSpecValueMapRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductSpecValueMapRequest) Reset()         { *m = DeleteProductSpecValueMapRequest{} }
func (m *DeleteProductSpecValueMapRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductSpecValueMapRequest) ProtoMessage()    {}
func (*DeleteProductSpecValueMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{20}
}
func (m *DeleteProductSpecValueMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductSpecValueMapRequest.Unmarshal(m, b)
}
func (m *DeleteProductSpecValueMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductSpecValueMapRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteProductSpecValueMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductSpecValueMapRequest.Merge(dst, src)
}
func (m *DeleteProductSpecValueMapRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductSpecValueMapRequest.Size(m)
}
func (m *DeleteProductSpecValueMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductSpecValueMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductSpecValueMapRequest proto.InternalMessageInfo

func (m *DeleteProductSpecValueMapRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteProductSpecValueMapResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductSpecValueMapResponse) Reset()         { *m = DeleteProductSpecValueMapResponse{} }
func (m *DeleteProductSpecValueMapResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProductSpecValueMapResponse) ProtoMessage()    {}
func (*DeleteProductSpecValueMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_value_a79f6495c281ac1d, []int{21}
}
func (m *DeleteProductSpecValueMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductSpecValueMapResponse.Unmarshal(m, b)
}
func (m *DeleteProductSpecValueMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductSpecValueMapResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteProductSpecValueMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductSpecValueMapResponse.Merge(dst, src)
}
func (m *DeleteProductSpecValueMapResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProductSpecValueMapResponse.Size(m)
}
func (m *DeleteProductSpecValueMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductSpecValueMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductSpecValueMapResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProductSpecValue)(nil), "ProductSpecValue")
	proto.RegisterType((*CreateProductSpecValueRequest)(nil), "CreateProductSpecValueRequest")
	proto.RegisterType((*CreateProductSpecValueResponse)(nil), "CreateProductSpecValueResponse")
	proto.RegisterType((*GetProductSpecValuesRequest)(nil), "GetProductSpecValuesRequest")
	proto.RegisterType((*GetProductSpecValuesResponse)(nil), "GetProductSpecValuesResponse")
	proto.RegisterType((*GetProductSpecValueByIdRequest)(nil), "GetProductSpecValueByIdRequest")
	proto.RegisterType((*GetProductSpecValueByIdResponse)(nil), "GetProductSpecValueByIdResponse")
	proto.RegisterType((*UpdateProductSpecValueRequest)(nil), "UpdateProductSpecValueRequest")
	proto.RegisterType((*UpdateProductSpecValueResponse)(nil), "UpdateProductSpecValueResponse")
	proto.RegisterType((*DeleteProductSpecValueRequest)(nil), "DeleteProductSpecValueRequest")
	proto.RegisterType((*DeleteProductSpecValueResponse)(nil), "DeleteProductSpecValueResponse")
	proto.RegisterType((*ProductSpecValueMap)(nil), "ProductSpecValueMap")
	proto.RegisterType((*CreateProductSpecValueMapRequest)(nil), "CreateProductSpecValueMapRequest")
	proto.RegisterType((*CreateProductSpecValueMapResponse)(nil), "CreateProductSpecValueMapResponse")
	proto.RegisterType((*GetProductSpecValueMapsRequest)(nil), "GetProductSpecValueMapsRequest")
	proto.RegisterType((*GetProductSpecValueMapsResponse)(nil), "GetProductSpecValueMapsResponse")
	proto.RegisterType((*GetProductSpecValueMapByIdRequest)(nil), "GetProductSpecValueMapByIdRequest")
	proto.RegisterType((*GetProductSpecValueMapByIdResponse)(nil), "GetProductSpecValueMapByIdResponse")
	proto.RegisterType((*UpdateProductSpecValueMapRequest)(nil), "UpdateProductSpecValueMapRequest")
	proto.RegisterType((*UpdateProductSpecValueMapResponse)(nil), "UpdateProductSpecValueMapResponse")
	proto.RegisterType((*DeleteProductSpecValueMapRequest)(nil), "DeleteProductSpecValueMapRequest")
	proto.RegisterType((*DeleteProductSpecValueMapResponse)(nil), "DeleteProductSpecValueMapResponse")
}

func init() {
	proto.RegisterFile("product_spec_value.proto", fileDescriptor_product_spec_value_a79f6495c281ac1d)
}

var fileDescriptor_product_spec_value_a79f6495c281ac1d = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x55, 0xec, 0x52, 0xe1, 0x01, 0x4a, 0xbb, 0x2d, 0x92, 0xa5, 0xd6, 0x61, 0xb3, 0xbd, 0xf4,
	0x42, 0x5a, 0xda, 0x1b, 0x07, 0x0e, 0x05, 0x09, 0xf9, 0x10, 0xa9, 0x4d, 0x44, 0x0f, 0x48, 0x34,
	0x2c, 0xde, 0x39, 0x58, 0x72, 0xe3, 0xc5, 0xeb, 0x58, 0xe2, 0x03, 0xf8, 0x6f, 0xd4, 0xf5, 0xba,
	0x71, 0xed, 0xb5, 0x93, 0x43, 0x6e, 0xeb, 0x9d, 0x79, 0x6f, 0xde, 0xce, 0xbc, 0x91, 0xc1, 0x97,
	0x59, 0x2a, 0x96, 0x51, 0x3e, 0x57, 0x12, 0xa3, 0x79, 0xc1, 0x93, 0x25, 0x8e, 0x65, 0x96, 0xe6,
	0x29, 0x43, 0xd8, 0xbf, 0x29, 0x63, 0x33, 0x89, 0xd1, 0xdd, 0x63, 0x84, 0xec, 0x81, 0x13, 0x0b,
	0x7f, 0x40, 0x07, 0x67, 0xee, 0xd4, 0x89, 0x05, 0x21, 0xb0, 0xb3, 0xe0, 0x0f, 0xe8, 0x3b, 0x74,
	0x70, 0xe6, 0x4d, 0xf5, 0x99, 0x7c, 0x80, 0xc3, 0x67, 0x9c, 0x0a, 0xf3, 0x79, 0x2c, 0x7c, 0x57,
	0x83, 0xf6, 0xe5, 0x8a, 0x72, 0x86, 0x79, 0x28, 0xd8, 0x2d, 0x04, 0x5f, 0x32, 0xe4, 0x39, 0x36,
	0x8b, 0x4d, 0xf1, 0xcf, 0x12, 0x55, 0x4e, 0x2e, 0x00, 0x56, 0xda, 0x74, 0xed, 0x57, 0x97, 0x07,
	0xe3, 0x56, 0xb6, 0xa7, 0xaa, 0x23, 0xa3, 0x30, 0xec, 0xa2, 0x54, 0x32, 0x5d, 0x28, 0x64, 0x01,
	0x1c, 0x7f, 0xc3, 0xbc, 0x19, 0x56, 0xa6, 0x24, 0xbb, 0x81, 0x13, 0x7b, 0xb8, 0x84, 0xb7, 0x24,
	0xb9, 0x6b, 0x25, 0x5d, 0xc0, 0xd0, 0xc2, 0x78, 0xfd, 0x37, 0x14, 0xd5, 0x33, 0x1b, 0xad, 0x65,
	0x33, 0x78, 0xdf, 0x89, 0xe8, 0x90, 0xb1, 0xbe, 0x33, 0xb7, 0x10, 0x7c, 0x97, 0x62, 0xdb, 0xcd,
	0xee, 0xa2, 0x34, 0xcd, 0x3e, 0x87, 0xe0, 0x2b, 0x26, 0xd8, 0x5d, 0xb4, 0xf9, 0x74, 0x0a, 0xc3,
	0x2e, 0x80, 0xa1, 0xfc, 0xe7, 0xc0, 0x61, 0x33, 0x38, 0xe1, 0xb2, 0xe5, 0xcf, 0x63, 0xf0, 0x0a,
	0x5c, 0x88, 0x34, 0x7b, 0x74, 0xa0, 0xa3, 0xaf, 0x5f, 0x96, 0x17, 0xa1, 0x20, 0x1f, 0xe1, 0x5d,
	0xdb, 0xfc, 0x2b, 0xab, 0x12, 0xd9, 0x28, 0x10, 0x0a, 0xf2, 0x19, 0x4e, 0x2a, 0x88, 0xe1, 0x7d,
	0x8e, 0xdc, 0xd1, 0xc8, 0x6a, 0xa7, 0xee, 0x74, 0x4a, 0x1d, 0x7f, 0x0e, 0x47, 0x56, 0xdc, 0x0b,
	0x8d, 0x3b, 0x28, 0x5a, 0x80, 0x00, 0xa0, 0x2a, 0x18, 0x0b, 0x7f, 0x57, 0xa7, 0x79, 0xe6, 0x26,
	0x14, 0xec, 0x1e, 0xa8, 0xdd, 0xe9, 0x13, 0x2e, 0xab, 0xee, 0x7e, 0x82, 0xbd, 0x5a, 0xb1, 0x07,
	0x2e, 0xcd, 0x58, 0x8f, 0xc6, 0x36, 0xd0, 0x6b, 0x55, 0xfb, 0x62, 0xa7, 0x30, 0xea, 0xe1, 0x37,
	0xc3, 0xa0, 0x56, 0x6f, 0x4f, 0xb8, 0x7c, 0xda, 0xa7, 0x9f, 0x56, 0x2f, 0x97, 0x19, 0xc6, 0xcb,
	0x36, 0x95, 0xee, 0x86, 0x2a, 0xaf, 0x60, 0x64, 0xa7, 0xef, 0xdb, 0xaf, 0x5f, 0xc0, 0xfa, 0x40,
	0x3d, 0xb2, 0x36, 0x6d, 0xde, 0x3d, 0x50, 0xfb, 0x66, 0x6c, 0x6f, 0x38, 0x3d, 0xfc, 0x66, 0x38,
	0x97, 0x40, 0xed, 0xbb, 0x54, 0x13, 0xd1, 0x6c, 0xcd, 0x29, 0x8c, 0x7a, 0x30, 0x25, 0xf1, 0xf5,
	0xdb, 0x1f, 0x6f, 0x92, 0x34, 0xe2, 0x89, 0xc2, 0xac, 0x88, 0x23, 0x54, 0xbf, 0x77, 0xf5, 0x6f,
	0xe3, 0xea, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x5c, 0xeb, 0x5d, 0x52, 0x06, 0x00, 0x00,
}
