// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package localservices

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocalServicesClient is the client API for LocalServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocalServicesClient interface {
	// Product
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
	GetProductDetail(ctx context.Context, in *GetProductDetailRequest, opts ...grpc.CallOption) (*GetProductDetailResponse, error)
	GetProductPrice(ctx context.Context, in *GetProductPriceRequest, opts ...grpc.CallOption) (*GetProductPriceResponse, error)
	// Category
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*Categories, error)
	GetCategoryMaps(ctx context.Context, in *GetCategoryMapsRequest, opts ...grpc.CallOption) (*GetCategoryMapsResponse, error)
	GetCategoryMapByID(ctx context.Context, in *GetCategoryMapByIdRequest, opts ...grpc.CallOption) (*GetCategoryMapByIdResponse, error)
	CreateCategoryMap(ctx context.Context, in *CreateCategoryMapRequest, opts ...grpc.CallOption) (*CreateCategoryMapResponse, error)
	UpdateCategoryMap(ctx context.Context, in *UpdateCategoryMapRequest, opts ...grpc.CallOption) (*UpdateCategoryMapResponse, error)
	DeleteCategoryMap(ctx context.Context, in *DeleteCategoryMapRequest, opts ...grpc.CallOption) (*DeleteCategoryMapResponse, error)
	// Order
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	// ProductSpecSet
	GetProductSpecSets(ctx context.Context, in *GetProductSpecSetsRequest, opts ...grpc.CallOption) (*GetProductSpecSetsResponse, error)
	GetProductSpecSetByID(ctx context.Context, in *GetProductSpecSetByIdRequest, opts ...grpc.CallOption) (*GetProductSpecSetByIdResponse, error)
	CreateProductSpecSet(ctx context.Context, in *CreateProductSpecSetRequest, opts ...grpc.CallOption) (*CreateProductSpecSetResponse, error)
	UpdateProductSpecSet(ctx context.Context, in *UpdateProductSpecSetRequest, opts ...grpc.CallOption) (*UpdateProductSpecSetResponse, error)
	DeleteProductSpecSet(ctx context.Context, in *DeleteProductSpecSetRequest, opts ...grpc.CallOption) (*DeleteProductSpecSetResponse, error)
	// ProductSpecSetMap
	GetProductSpecSetMaps(ctx context.Context, in *GetProductSpecSetMapsRequest, opts ...grpc.CallOption) (*GetProductSpecSetMapsResponse, error)
	GetProductSpecSetMapByID(ctx context.Context, in *GetProductSpecSetMapByIdRequest, opts ...grpc.CallOption) (*GetProductSpecSetMapByIdResponse, error)
	CreateProductSpecSetMap(ctx context.Context, in *CreateProductSpecSetMapRequest, opts ...grpc.CallOption) (*CreateProductSpecSetMapResponse, error)
	UpdateProductSpecSetMap(ctx context.Context, in *UpdateProductSpecSetMapRequest, opts ...grpc.CallOption) (*UpdateProductSpecSetMapResponse, error)
	DeleteProductSpecSetMap(ctx context.Context, in *DeleteProductSpecSetMapRequest, opts ...grpc.CallOption) (*DeleteProductSpecSetMapResponse, error)
	// ProductSpecValue
	GetProductSpecValues(ctx context.Context, in *GetProductSpecValuesRequest, opts ...grpc.CallOption) (*GetProductSpecValuesResponse, error)
	GetProductSpecValueByID(ctx context.Context, in *GetProductSpecValueByIdRequest, opts ...grpc.CallOption) (*GetProductSpecValueByIdResponse, error)
	CreateProductSpecValue(ctx context.Context, in *CreateProductSpecValueRequest, opts ...grpc.CallOption) (*CreateProductSpecValueResponse, error)
	UpdateProductSpecValue(ctx context.Context, in *UpdateProductSpecValueRequest, opts ...grpc.CallOption) (*UpdateProductSpecValueResponse, error)
	DeleteProductSpecValue(ctx context.Context, in *DeleteProductSpecValueRequest, opts ...grpc.CallOption) (*DeleteProductSpecValueResponse, error)
	// ProductSpecValueMap
	GetProductSpecValueMaps(ctx context.Context, in *GetProductSpecValueMapsRequest, opts ...grpc.CallOption) (*GetProductSpecValueMapsResponse, error)
	GetProductSpecValueMapByID(ctx context.Context, in *GetProductSpecValueMapByIdRequest, opts ...grpc.CallOption) (*GetProductSpecValueMapByIdResponse, error)
	CreateProductSpecValueMap(ctx context.Context, in *CreateProductSpecValueMapRequest, opts ...grpc.CallOption) (*CreateProductSpecValueMapResponse, error)
	UpdateProductSpecValueMap(ctx context.Context, in *UpdateProductSpecValueMapRequest, opts ...grpc.CallOption) (*UpdateProductSpecValueMapResponse, error)
	DeleteProductSpecValueMap(ctx context.Context, in *DeleteProductSpecValueMapRequest, opts ...grpc.CallOption) (*DeleteProductSpecValueMapResponse, error)
	// Payment
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	CreatePaymentDetail(ctx context.Context, in *CreatePaymentDetailRequest, opts ...grpc.CallOption) (*CreatePaymentDetailResponse, error)
	GetPaymentData(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error)
	GetPaymentDetail(ctx context.Context, in *GetPaymentDetailRequest, opts ...grpc.CallOption) (*GetPaymentDetailResponse, error)
	GetPaymentDetailByPayment(ctx context.Context, in *GetPaymentDetailRequest, opts ...grpc.CallOption) (*GetPaymentDetailsResponse, error)
	UpdatePaymentData(ctx context.Context, in *UpdatePaymentDataRequest, opts ...grpc.CallOption) (*UpdatePaymentDataResponse, error)
	UpdatePaymentDetail(ctx context.Context, in *UpdatePaymentDetailRequest, opts ...grpc.CallOption) (*UpdatePaymentDetailResponse, error)
	// TransactionFulfillment
	GetTxFulfillments(ctx context.Context, in *GetTxFulfillmentsRequest, opts ...grpc.CallOption) (*GetTxFulfillmentsResponse, error)
	GetTxFulfillmentById(ctx context.Context, in *GetTxFulfillmentByIdRequest, opts ...grpc.CallOption) (*GetTxFulfillmentByIdResponse, error)
	CreateTxFulfillment(ctx context.Context, in *CreateTxFulfillmentRequest, opts ...grpc.CallOption) (*CreateTxFulfillmentResponse, error)
	UpdateTxFulfillment(ctx context.Context, in *UpdateTxFulfillmentRequest, opts ...grpc.CallOption) (*UpdateTxFulfillmentResponse, error)
	// VendorSubprovinceCoverage
	GetVendorSubprovinceCoverages(ctx context.Context, in *GetVendorSubprovinceCoveragesRequest, opts ...grpc.CallOption) (*GetVendorSubprovinceCoveragesResponse, error)
	GetVendorSubprovinceCoverageByID(ctx context.Context, in *GetVendorSubprovinceCoverageByIdRequest, opts ...grpc.CallOption) (*GetVendorSubprovinceCoverageByIdResponse, error)
	CreateVendorSubprovinceCoverage(ctx context.Context, in *CreateVendorSubprovinceCoverageRequest, opts ...grpc.CallOption) (*CreateVendorSubprovinceCoverageResponse, error)
	UpdateVendorSubprovinceCoverage(ctx context.Context, in *UpdateVendorSubprovinceCoverageRequest, opts ...grpc.CallOption) (*UpdateVendorSubprovinceCoverageResponse, error)
	// Checkout Internal
	CheckoutValidation(ctx context.Context, in *CheckoutValidationRequest, opts ...grpc.CallOption) (*CheckoutValidationResponse, error)
}

type localServicesClient struct {
	cc *grpc.ClientConn
}

func NewLocalServicesClient(cc *grpc.ClientConn) LocalServicesClient {
	return &localServicesClient{cc}
}

func (c *localServicesClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetProductDetail(ctx context.Context, in *GetProductDetailRequest, opts ...grpc.CallOption) (*GetProductDetailResponse, error) {
	out := new(GetProductDetailResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProductDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetProductPrice(ctx context.Context, in *GetProductPriceRequest, opts ...grpc.CallOption) (*GetProductPriceResponse, error) {
	out := new(GetProductPriceResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProductPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*Categories, error) {
	out := new(Categories)
	err := c.cc.Invoke(ctx, "/LocalServices/GetCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetCategoryMaps(ctx context.Context, in *GetCategoryMapsRequest, opts ...grpc.CallOption) (*GetCategoryMapsResponse, error) {
	out := new(GetCategoryMapsResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetCategoryMaps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetCategoryMapByID(ctx context.Context, in *GetCategoryMapByIdRequest, opts ...grpc.CallOption) (*GetCategoryMapByIdResponse, error) {
	out := new(GetCategoryMapByIdResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetCategoryMapByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CreateCategoryMap(ctx context.Context, in *CreateCategoryMapRequest, opts ...grpc.CallOption) (*CreateCategoryMapResponse, error) {
	out := new(CreateCategoryMapResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CreateCategoryMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) UpdateCategoryMap(ctx context.Context, in *UpdateCategoryMapRequest, opts ...grpc.CallOption) (*UpdateCategoryMapResponse, error) {
	out := new(UpdateCategoryMapResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/UpdateCategoryMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) DeleteCategoryMap(ctx context.Context, in *DeleteCategoryMapRequest, opts ...grpc.CallOption) (*DeleteCategoryMapResponse, error) {
	out := new(DeleteCategoryMapResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/DeleteCategoryMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/LocalServices/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetProductSpecSets(ctx context.Context, in *GetProductSpecSetsRequest, opts ...grpc.CallOption) (*GetProductSpecSetsResponse, error) {
	out := new(GetProductSpecSetsResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProductSpecSets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetProductSpecSetByID(ctx context.Context, in *GetProductSpecSetByIdRequest, opts ...grpc.CallOption) (*GetProductSpecSetByIdResponse, error) {
	out := new(GetProductSpecSetByIdResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProductSpecSetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CreateProductSpecSet(ctx context.Context, in *CreateProductSpecSetRequest, opts ...grpc.CallOption) (*CreateProductSpecSetResponse, error) {
	out := new(CreateProductSpecSetResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CreateProductSpecSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) UpdateProductSpecSet(ctx context.Context, in *UpdateProductSpecSetRequest, opts ...grpc.CallOption) (*UpdateProductSpecSetResponse, error) {
	out := new(UpdateProductSpecSetResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/UpdateProductSpecSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) DeleteProductSpecSet(ctx context.Context, in *DeleteProductSpecSetRequest, opts ...grpc.CallOption) (*DeleteProductSpecSetResponse, error) {
	out := new(DeleteProductSpecSetResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/DeleteProductSpecSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetProductSpecSetMaps(ctx context.Context, in *GetProductSpecSetMapsRequest, opts ...grpc.CallOption) (*GetProductSpecSetMapsResponse, error) {
	out := new(GetProductSpecSetMapsResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProductSpecSetMaps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetProductSpecSetMapByID(ctx context.Context, in *GetProductSpecSetMapByIdRequest, opts ...grpc.CallOption) (*GetProductSpecSetMapByIdResponse, error) {
	out := new(GetProductSpecSetMapByIdResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProductSpecSetMapByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CreateProductSpecSetMap(ctx context.Context, in *CreateProductSpecSetMapRequest, opts ...grpc.CallOption) (*CreateProductSpecSetMapResponse, error) {
	out := new(CreateProductSpecSetMapResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CreateProductSpecSetMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) UpdateProductSpecSetMap(ctx context.Context, in *UpdateProductSpecSetMapRequest, opts ...grpc.CallOption) (*UpdateProductSpecSetMapResponse, error) {
	out := new(UpdateProductSpecSetMapResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/UpdateProductSpecSetMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) DeleteProductSpecSetMap(ctx context.Context, in *DeleteProductSpecSetMapRequest, opts ...grpc.CallOption) (*DeleteProductSpecSetMapResponse, error) {
	out := new(DeleteProductSpecSetMapResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/DeleteProductSpecSetMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetProductSpecValues(ctx context.Context, in *GetProductSpecValuesRequest, opts ...grpc.CallOption) (*GetProductSpecValuesResponse, error) {
	out := new(GetProductSpecValuesResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProductSpecValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetProductSpecValueByID(ctx context.Context, in *GetProductSpecValueByIdRequest, opts ...grpc.CallOption) (*GetProductSpecValueByIdResponse, error) {
	out := new(GetProductSpecValueByIdResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProductSpecValueByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CreateProductSpecValue(ctx context.Context, in *CreateProductSpecValueRequest, opts ...grpc.CallOption) (*CreateProductSpecValueResponse, error) {
	out := new(CreateProductSpecValueResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CreateProductSpecValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) UpdateProductSpecValue(ctx context.Context, in *UpdateProductSpecValueRequest, opts ...grpc.CallOption) (*UpdateProductSpecValueResponse, error) {
	out := new(UpdateProductSpecValueResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/UpdateProductSpecValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) DeleteProductSpecValue(ctx context.Context, in *DeleteProductSpecValueRequest, opts ...grpc.CallOption) (*DeleteProductSpecValueResponse, error) {
	out := new(DeleteProductSpecValueResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/DeleteProductSpecValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetProductSpecValueMaps(ctx context.Context, in *GetProductSpecValueMapsRequest, opts ...grpc.CallOption) (*GetProductSpecValueMapsResponse, error) {
	out := new(GetProductSpecValueMapsResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProductSpecValueMaps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetProductSpecValueMapByID(ctx context.Context, in *GetProductSpecValueMapByIdRequest, opts ...grpc.CallOption) (*GetProductSpecValueMapByIdResponse, error) {
	out := new(GetProductSpecValueMapByIdResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetProductSpecValueMapByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CreateProductSpecValueMap(ctx context.Context, in *CreateProductSpecValueMapRequest, opts ...grpc.CallOption) (*CreateProductSpecValueMapResponse, error) {
	out := new(CreateProductSpecValueMapResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CreateProductSpecValueMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) UpdateProductSpecValueMap(ctx context.Context, in *UpdateProductSpecValueMapRequest, opts ...grpc.CallOption) (*UpdateProductSpecValueMapResponse, error) {
	out := new(UpdateProductSpecValueMapResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/UpdateProductSpecValueMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) DeleteProductSpecValueMap(ctx context.Context, in *DeleteProductSpecValueMapRequest, opts ...grpc.CallOption) (*DeleteProductSpecValueMapResponse, error) {
	out := new(DeleteProductSpecValueMapResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/DeleteProductSpecValueMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CreatePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CreatePaymentDetail(ctx context.Context, in *CreatePaymentDetailRequest, opts ...grpc.CallOption) (*CreatePaymentDetailResponse, error) {
	out := new(CreatePaymentDetailResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CreatePaymentDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetPaymentData(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error) {
	out := new(GetPaymentResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetPaymentData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetPaymentDetail(ctx context.Context, in *GetPaymentDetailRequest, opts ...grpc.CallOption) (*GetPaymentDetailResponse, error) {
	out := new(GetPaymentDetailResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetPaymentDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetPaymentDetailByPayment(ctx context.Context, in *GetPaymentDetailRequest, opts ...grpc.CallOption) (*GetPaymentDetailsResponse, error) {
	out := new(GetPaymentDetailsResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetPaymentDetailByPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) UpdatePaymentData(ctx context.Context, in *UpdatePaymentDataRequest, opts ...grpc.CallOption) (*UpdatePaymentDataResponse, error) {
	out := new(UpdatePaymentDataResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/UpdatePaymentData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) UpdatePaymentDetail(ctx context.Context, in *UpdatePaymentDetailRequest, opts ...grpc.CallOption) (*UpdatePaymentDetailResponse, error) {
	out := new(UpdatePaymentDetailResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/UpdatePaymentDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetTxFulfillments(ctx context.Context, in *GetTxFulfillmentsRequest, opts ...grpc.CallOption) (*GetTxFulfillmentsResponse, error) {
	out := new(GetTxFulfillmentsResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetTxFulfillments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetTxFulfillmentById(ctx context.Context, in *GetTxFulfillmentByIdRequest, opts ...grpc.CallOption) (*GetTxFulfillmentByIdResponse, error) {
	out := new(GetTxFulfillmentByIdResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetTxFulfillmentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CreateTxFulfillment(ctx context.Context, in *CreateTxFulfillmentRequest, opts ...grpc.CallOption) (*CreateTxFulfillmentResponse, error) {
	out := new(CreateTxFulfillmentResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CreateTxFulfillment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) UpdateTxFulfillment(ctx context.Context, in *UpdateTxFulfillmentRequest, opts ...grpc.CallOption) (*UpdateTxFulfillmentResponse, error) {
	out := new(UpdateTxFulfillmentResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/UpdateTxFulfillment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetVendorSubprovinceCoverages(ctx context.Context, in *GetVendorSubprovinceCoveragesRequest, opts ...grpc.CallOption) (*GetVendorSubprovinceCoveragesResponse, error) {
	out := new(GetVendorSubprovinceCoveragesResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetVendorSubprovinceCoverages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) GetVendorSubprovinceCoverageByID(ctx context.Context, in *GetVendorSubprovinceCoverageByIdRequest, opts ...grpc.CallOption) (*GetVendorSubprovinceCoverageByIdResponse, error) {
	out := new(GetVendorSubprovinceCoverageByIdResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/GetVendorSubprovinceCoverageByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CreateVendorSubprovinceCoverage(ctx context.Context, in *CreateVendorSubprovinceCoverageRequest, opts ...grpc.CallOption) (*CreateVendorSubprovinceCoverageResponse, error) {
	out := new(CreateVendorSubprovinceCoverageResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CreateVendorSubprovinceCoverage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) UpdateVendorSubprovinceCoverage(ctx context.Context, in *UpdateVendorSubprovinceCoverageRequest, opts ...grpc.CallOption) (*UpdateVendorSubprovinceCoverageResponse, error) {
	out := new(UpdateVendorSubprovinceCoverageResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/UpdateVendorSubprovinceCoverage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localServicesClient) CheckoutValidation(ctx context.Context, in *CheckoutValidationRequest, opts ...grpc.CallOption) (*CheckoutValidationResponse, error) {
	out := new(CheckoutValidationResponse)
	err := c.cc.Invoke(ctx, "/LocalServices/CheckoutValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalServicesServer is the server API for LocalServices service.
type LocalServicesServer interface {
	// Product
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	GetProductDetail(context.Context, *GetProductDetailRequest) (*GetProductDetailResponse, error)
	GetProductPrice(context.Context, *GetProductPriceRequest) (*GetProductPriceResponse, error)
	// Category
	GetCategories(context.Context, *GetCategoriesRequest) (*Categories, error)
	GetCategoryMaps(context.Context, *GetCategoryMapsRequest) (*GetCategoryMapsResponse, error)
	GetCategoryMapByID(context.Context, *GetCategoryMapByIdRequest) (*GetCategoryMapByIdResponse, error)
	CreateCategoryMap(context.Context, *CreateCategoryMapRequest) (*CreateCategoryMapResponse, error)
	UpdateCategoryMap(context.Context, *UpdateCategoryMapRequest) (*UpdateCategoryMapResponse, error)
	DeleteCategoryMap(context.Context, *DeleteCategoryMapRequest) (*DeleteCategoryMapResponse, error)
	// Order
	GetOrder(context.Context, *GetOrderRequest) (*Order, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	// ProductSpecSet
	GetProductSpecSets(context.Context, *GetProductSpecSetsRequest) (*GetProductSpecSetsResponse, error)
	GetProductSpecSetByID(context.Context, *GetProductSpecSetByIdRequest) (*GetProductSpecSetByIdResponse, error)
	CreateProductSpecSet(context.Context, *CreateProductSpecSetRequest) (*CreateProductSpecSetResponse, error)
	UpdateProductSpecSet(context.Context, *UpdateProductSpecSetRequest) (*UpdateProductSpecSetResponse, error)
	DeleteProductSpecSet(context.Context, *DeleteProductSpecSetRequest) (*DeleteProductSpecSetResponse, error)
	// ProductSpecSetMap
	GetProductSpecSetMaps(context.Context, *GetProductSpecSetMapsRequest) (*GetProductSpecSetMapsResponse, error)
	GetProductSpecSetMapByID(context.Context, *GetProductSpecSetMapByIdRequest) (*GetProductSpecSetMapByIdResponse, error)
	CreateProductSpecSetMap(context.Context, *CreateProductSpecSetMapRequest) (*CreateProductSpecSetMapResponse, error)
	UpdateProductSpecSetMap(context.Context, *UpdateProductSpecSetMapRequest) (*UpdateProductSpecSetMapResponse, error)
	DeleteProductSpecSetMap(context.Context, *DeleteProductSpecSetMapRequest) (*DeleteProductSpecSetMapResponse, error)
	// ProductSpecValue
	GetProductSpecValues(context.Context, *GetProductSpecValuesRequest) (*GetProductSpecValuesResponse, error)
	GetProductSpecValueByID(context.Context, *GetProductSpecValueByIdRequest) (*GetProductSpecValueByIdResponse, error)
	CreateProductSpecValue(context.Context, *CreateProductSpecValueRequest) (*CreateProductSpecValueResponse, error)
	UpdateProductSpecValue(context.Context, *UpdateProductSpecValueRequest) (*UpdateProductSpecValueResponse, error)
	DeleteProductSpecValue(context.Context, *DeleteProductSpecValueRequest) (*DeleteProductSpecValueResponse, error)
	// ProductSpecValueMap
	GetProductSpecValueMaps(context.Context, *GetProductSpecValueMapsRequest) (*GetProductSpecValueMapsResponse, error)
	GetProductSpecValueMapByID(context.Context, *GetProductSpecValueMapByIdRequest) (*GetProductSpecValueMapByIdResponse, error)
	CreateProductSpecValueMap(context.Context, *CreateProductSpecValueMapRequest) (*CreateProductSpecValueMapResponse, error)
	UpdateProductSpecValueMap(context.Context, *UpdateProductSpecValueMapRequest) (*UpdateProductSpecValueMapResponse, error)
	DeleteProductSpecValueMap(context.Context, *DeleteProductSpecValueMapRequest) (*DeleteProductSpecValueMapResponse, error)
	// Payment
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	CreatePaymentDetail(context.Context, *CreatePaymentDetailRequest) (*CreatePaymentDetailResponse, error)
	GetPaymentData(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error)
	GetPaymentDetail(context.Context, *GetPaymentDetailRequest) (*GetPaymentDetailResponse, error)
	GetPaymentDetailByPayment(context.Context, *GetPaymentDetailRequest) (*GetPaymentDetailsResponse, error)
	UpdatePaymentData(context.Context, *UpdatePaymentDataRequest) (*UpdatePaymentDataResponse, error)
	UpdatePaymentDetail(context.Context, *UpdatePaymentDetailRequest) (*UpdatePaymentDetailResponse, error)
	// TransactionFulfillment
	GetTxFulfillments(context.Context, *GetTxFulfillmentsRequest) (*GetTxFulfillmentsResponse, error)
	GetTxFulfillmentById(context.Context, *GetTxFulfillmentByIdRequest) (*GetTxFulfillmentByIdResponse, error)
	CreateTxFulfillment(context.Context, *CreateTxFulfillmentRequest) (*CreateTxFulfillmentResponse, error)
	UpdateTxFulfillment(context.Context, *UpdateTxFulfillmentRequest) (*UpdateTxFulfillmentResponse, error)
	// VendorSubprovinceCoverage
	GetVendorSubprovinceCoverages(context.Context, *GetVendorSubprovinceCoveragesRequest) (*GetVendorSubprovinceCoveragesResponse, error)
	GetVendorSubprovinceCoverageByID(context.Context, *GetVendorSubprovinceCoverageByIdRequest) (*GetVendorSubprovinceCoverageByIdResponse, error)
	CreateVendorSubprovinceCoverage(context.Context, *CreateVendorSubprovinceCoverageRequest) (*CreateVendorSubprovinceCoverageResponse, error)
	UpdateVendorSubprovinceCoverage(context.Context, *UpdateVendorSubprovinceCoverageRequest) (*UpdateVendorSubprovinceCoverageResponse, error)
	// Checkout Internal
	CheckoutValidation(context.Context, *CheckoutValidationRequest) (*CheckoutValidationResponse, error)
}

func RegisterLocalServicesServer(s *grpc.Server, srv LocalServicesServer) {
	s.RegisterService(&_LocalServices_serviceDesc, srv)
}

func _LocalServices_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetProductDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProductDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProductDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProductDetail(ctx, req.(*GetProductDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetProductPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProductPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProductPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProductPrice(ctx, req.(*GetProductPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetCategoryMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryMapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetCategoryMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetCategoryMaps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetCategoryMaps(ctx, req.(*GetCategoryMapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetCategoryMapByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryMapByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetCategoryMapByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetCategoryMapByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetCategoryMapByID(ctx, req.(*GetCategoryMapByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CreateCategoryMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CreateCategoryMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CreateCategoryMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CreateCategoryMap(ctx, req.(*CreateCategoryMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_UpdateCategoryMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).UpdateCategoryMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/UpdateCategoryMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).UpdateCategoryMap(ctx, req.(*UpdateCategoryMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_DeleteCategoryMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).DeleteCategoryMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/DeleteCategoryMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).DeleteCategoryMap(ctx, req.(*DeleteCategoryMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetProductSpecSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductSpecSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProductSpecSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProductSpecSets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProductSpecSets(ctx, req.(*GetProductSpecSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetProductSpecSetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductSpecSetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProductSpecSetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProductSpecSetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProductSpecSetByID(ctx, req.(*GetProductSpecSetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CreateProductSpecSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductSpecSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CreateProductSpecSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CreateProductSpecSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CreateProductSpecSet(ctx, req.(*CreateProductSpecSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_UpdateProductSpecSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductSpecSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).UpdateProductSpecSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/UpdateProductSpecSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).UpdateProductSpecSet(ctx, req.(*UpdateProductSpecSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_DeleteProductSpecSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductSpecSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).DeleteProductSpecSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/DeleteProductSpecSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).DeleteProductSpecSet(ctx, req.(*DeleteProductSpecSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetProductSpecSetMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductSpecSetMapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProductSpecSetMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProductSpecSetMaps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProductSpecSetMaps(ctx, req.(*GetProductSpecSetMapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetProductSpecSetMapByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductSpecSetMapByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProductSpecSetMapByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProductSpecSetMapByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProductSpecSetMapByID(ctx, req.(*GetProductSpecSetMapByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CreateProductSpecSetMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductSpecSetMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CreateProductSpecSetMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CreateProductSpecSetMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CreateProductSpecSetMap(ctx, req.(*CreateProductSpecSetMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_UpdateProductSpecSetMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductSpecSetMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).UpdateProductSpecSetMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/UpdateProductSpecSetMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).UpdateProductSpecSetMap(ctx, req.(*UpdateProductSpecSetMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_DeleteProductSpecSetMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductSpecSetMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).DeleteProductSpecSetMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/DeleteProductSpecSetMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).DeleteProductSpecSetMap(ctx, req.(*DeleteProductSpecSetMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetProductSpecValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductSpecValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProductSpecValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProductSpecValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProductSpecValues(ctx, req.(*GetProductSpecValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetProductSpecValueByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductSpecValueByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProductSpecValueByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProductSpecValueByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProductSpecValueByID(ctx, req.(*GetProductSpecValueByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CreateProductSpecValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductSpecValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CreateProductSpecValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CreateProductSpecValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CreateProductSpecValue(ctx, req.(*CreateProductSpecValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_UpdateProductSpecValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductSpecValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).UpdateProductSpecValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/UpdateProductSpecValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).UpdateProductSpecValue(ctx, req.(*UpdateProductSpecValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_DeleteProductSpecValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductSpecValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).DeleteProductSpecValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/DeleteProductSpecValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).DeleteProductSpecValue(ctx, req.(*DeleteProductSpecValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetProductSpecValueMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductSpecValueMapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProductSpecValueMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProductSpecValueMaps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProductSpecValueMaps(ctx, req.(*GetProductSpecValueMapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetProductSpecValueMapByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductSpecValueMapByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetProductSpecValueMapByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetProductSpecValueMapByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetProductSpecValueMapByID(ctx, req.(*GetProductSpecValueMapByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CreateProductSpecValueMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductSpecValueMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CreateProductSpecValueMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CreateProductSpecValueMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CreateProductSpecValueMap(ctx, req.(*CreateProductSpecValueMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_UpdateProductSpecValueMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductSpecValueMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).UpdateProductSpecValueMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/UpdateProductSpecValueMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).UpdateProductSpecValueMap(ctx, req.(*UpdateProductSpecValueMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_DeleteProductSpecValueMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductSpecValueMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).DeleteProductSpecValueMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/DeleteProductSpecValueMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).DeleteProductSpecValueMap(ctx, req.(*DeleteProductSpecValueMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CreatePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CreatePaymentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CreatePaymentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CreatePaymentDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CreatePaymentDetail(ctx, req.(*CreatePaymentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetPaymentData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetPaymentData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetPaymentData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetPaymentData(ctx, req.(*GetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetPaymentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetPaymentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetPaymentDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetPaymentDetail(ctx, req.(*GetPaymentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetPaymentDetailByPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetPaymentDetailByPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetPaymentDetailByPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetPaymentDetailByPayment(ctx, req.(*GetPaymentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_UpdatePaymentData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).UpdatePaymentData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/UpdatePaymentData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).UpdatePaymentData(ctx, req.(*UpdatePaymentDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_UpdatePaymentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).UpdatePaymentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/UpdatePaymentDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).UpdatePaymentDetail(ctx, req.(*UpdatePaymentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetTxFulfillments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxFulfillmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetTxFulfillments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetTxFulfillments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetTxFulfillments(ctx, req.(*GetTxFulfillmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetTxFulfillmentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxFulfillmentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetTxFulfillmentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetTxFulfillmentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetTxFulfillmentById(ctx, req.(*GetTxFulfillmentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CreateTxFulfillment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTxFulfillmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CreateTxFulfillment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CreateTxFulfillment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CreateTxFulfillment(ctx, req.(*CreateTxFulfillmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_UpdateTxFulfillment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTxFulfillmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).UpdateTxFulfillment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/UpdateTxFulfillment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).UpdateTxFulfillment(ctx, req.(*UpdateTxFulfillmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetVendorSubprovinceCoverages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendorSubprovinceCoveragesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetVendorSubprovinceCoverages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetVendorSubprovinceCoverages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetVendorSubprovinceCoverages(ctx, req.(*GetVendorSubprovinceCoveragesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_GetVendorSubprovinceCoverageByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendorSubprovinceCoverageByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).GetVendorSubprovinceCoverageByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/GetVendorSubprovinceCoverageByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).GetVendorSubprovinceCoverageByID(ctx, req.(*GetVendorSubprovinceCoverageByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CreateVendorSubprovinceCoverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVendorSubprovinceCoverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CreateVendorSubprovinceCoverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CreateVendorSubprovinceCoverage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CreateVendorSubprovinceCoverage(ctx, req.(*CreateVendorSubprovinceCoverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_UpdateVendorSubprovinceCoverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVendorSubprovinceCoverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).UpdateVendorSubprovinceCoverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/UpdateVendorSubprovinceCoverage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).UpdateVendorSubprovinceCoverage(ctx, req.(*UpdateVendorSubprovinceCoverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalServices_CheckoutValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalServicesServer).CheckoutValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalServices/CheckoutValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalServicesServer).CheckoutValidation(ctx, req.(*CheckoutValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LocalServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LocalServices",
	HandlerType: (*LocalServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _LocalServices_GetProducts_Handler,
		},
		{
			MethodName: "GetProductDetail",
			Handler:    _LocalServices_GetProductDetail_Handler,
		},
		{
			MethodName: "GetProductPrice",
			Handler:    _LocalServices_GetProductPrice_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _LocalServices_GetCategories_Handler,
		},
		{
			MethodName: "GetCategoryMaps",
			Handler:    _LocalServices_GetCategoryMaps_Handler,
		},
		{
			MethodName: "GetCategoryMapByID",
			Handler:    _LocalServices_GetCategoryMapByID_Handler,
		},
		{
			MethodName: "CreateCategoryMap",
			Handler:    _LocalServices_CreateCategoryMap_Handler,
		},
		{
			MethodName: "UpdateCategoryMap",
			Handler:    _LocalServices_UpdateCategoryMap_Handler,
		},
		{
			MethodName: "DeleteCategoryMap",
			Handler:    _LocalServices_DeleteCategoryMap_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _LocalServices_GetOrder_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _LocalServices_CreateOrder_Handler,
		},
		{
			MethodName: "GetProductSpecSets",
			Handler:    _LocalServices_GetProductSpecSets_Handler,
		},
		{
			MethodName: "GetProductSpecSetByID",
			Handler:    _LocalServices_GetProductSpecSetByID_Handler,
		},
		{
			MethodName: "CreateProductSpecSet",
			Handler:    _LocalServices_CreateProductSpecSet_Handler,
		},
		{
			MethodName: "UpdateProductSpecSet",
			Handler:    _LocalServices_UpdateProductSpecSet_Handler,
		},
		{
			MethodName: "DeleteProductSpecSet",
			Handler:    _LocalServices_DeleteProductSpecSet_Handler,
		},
		{
			MethodName: "GetProductSpecSetMaps",
			Handler:    _LocalServices_GetProductSpecSetMaps_Handler,
		},
		{
			MethodName: "GetProductSpecSetMapByID",
			Handler:    _LocalServices_GetProductSpecSetMapByID_Handler,
		},
		{
			MethodName: "CreateProductSpecSetMap",
			Handler:    _LocalServices_CreateProductSpecSetMap_Handler,
		},
		{
			MethodName: "UpdateProductSpecSetMap",
			Handler:    _LocalServices_UpdateProductSpecSetMap_Handler,
		},
		{
			MethodName: "DeleteProductSpecSetMap",
			Handler:    _LocalServices_DeleteProductSpecSetMap_Handler,
		},
		{
			MethodName: "GetProductSpecValues",
			Handler:    _LocalServices_GetProductSpecValues_Handler,
		},
		{
			MethodName: "GetProductSpecValueByID",
			Handler:    _LocalServices_GetProductSpecValueByID_Handler,
		},
		{
			MethodName: "CreateProductSpecValue",
			Handler:    _LocalServices_CreateProductSpecValue_Handler,
		},
		{
			MethodName: "UpdateProductSpecValue",
			Handler:    _LocalServices_UpdateProductSpecValue_Handler,
		},
		{
			MethodName: "DeleteProductSpecValue",
			Handler:    _LocalServices_DeleteProductSpecValue_Handler,
		},
		{
			MethodName: "GetProductSpecValueMaps",
			Handler:    _LocalServices_GetProductSpecValueMaps_Handler,
		},
		{
			MethodName: "GetProductSpecValueMapByID",
			Handler:    _LocalServices_GetProductSpecValueMapByID_Handler,
		},
		{
			MethodName: "CreateProductSpecValueMap",
			Handler:    _LocalServices_CreateProductSpecValueMap_Handler,
		},
		{
			MethodName: "UpdateProductSpecValueMap",
			Handler:    _LocalServices_UpdateProductSpecValueMap_Handler,
		},
		{
			MethodName: "DeleteProductSpecValueMap",
			Handler:    _LocalServices_DeleteProductSpecValueMap_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _LocalServices_CreatePayment_Handler,
		},
		{
			MethodName: "CreatePaymentDetail",
			Handler:    _LocalServices_CreatePaymentDetail_Handler,
		},
		{
			MethodName: "GetPaymentData",
			Handler:    _LocalServices_GetPaymentData_Handler,
		},
		{
			MethodName: "GetPaymentDetail",
			Handler:    _LocalServices_GetPaymentDetail_Handler,
		},
		{
			MethodName: "GetPaymentDetailByPayment",
			Handler:    _LocalServices_GetPaymentDetailByPayment_Handler,
		},
		{
			MethodName: "UpdatePaymentData",
			Handler:    _LocalServices_UpdatePaymentData_Handler,
		},
		{
			MethodName: "UpdatePaymentDetail",
			Handler:    _LocalServices_UpdatePaymentDetail_Handler,
		},
		{
			MethodName: "GetTxFulfillments",
			Handler:    _LocalServices_GetTxFulfillments_Handler,
		},
		{
			MethodName: "GetTxFulfillmentById",
			Handler:    _LocalServices_GetTxFulfillmentById_Handler,
		},
		{
			MethodName: "CreateTxFulfillment",
			Handler:    _LocalServices_CreateTxFulfillment_Handler,
		},
		{
			MethodName: "UpdateTxFulfillment",
			Handler:    _LocalServices_UpdateTxFulfillment_Handler,
		},
		{
			MethodName: "GetVendorSubprovinceCoverages",
			Handler:    _LocalServices_GetVendorSubprovinceCoverages_Handler,
		},
		{
			MethodName: "GetVendorSubprovinceCoverageByID",
			Handler:    _LocalServices_GetVendorSubprovinceCoverageByID_Handler,
		},
		{
			MethodName: "CreateVendorSubprovinceCoverage",
			Handler:    _LocalServices_CreateVendorSubprovinceCoverage_Handler,
		},
		{
			MethodName: "UpdateVendorSubprovinceCoverage",
			Handler:    _LocalServices_UpdateVendorSubprovinceCoverage_Handler,
		},
		{
			MethodName: "CheckoutValidation",
			Handler:    _LocalServices_CheckoutValidation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_faca1b9666c20f96) }

var fileDescriptor_service_faca1b9666c20f96 = []byte{
	// 933 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0x5d, 0x6f, 0x23, 0x35,
	0x14, 0xdd, 0xa7, 0x15, 0x72, 0x95, 0xdd, 0xae, 0xb3, 0xed, 0x26, 0xe9, 0x47, 0xd2, 0x20, 0x4a,
	0x79, 0xf1, 0x03, 0x88, 0x17, 0x78, 0x41, 0x4d, 0xd5, 0xa8, 0x52, 0x51, 0xab, 0x86, 0x56, 0x08,
	0x24, 0x2a, 0x77, 0xc6, 0x94, 0x11, 0xc3, 0xcc, 0x30, 0x76, 0x22, 0xf2, 0x77, 0xf9, 0x25, 0x68,
	0xc6, 0xe3, 0xef, 0xeb, 0x09, 0x6f, 0xeb, 0x73, 0x4e, 0xce, 0xb5, 0xef, 0xb1, 0x77, 0xec, 0xa2,
	0x01, 0x67, 0xf5, 0x26, 0x4b, 0x18, 0xa9, 0xea, 0x52, 0x94, 0x93, 0x77, 0x55, 0x5d, 0xa6, 0xeb,
	0x44, 0xf0, 0x6e, 0x3c, 0xec, 0xc6, 0xcf, 0x55, 0x6d, 0x44, 0x87, 0x0a, 0xe4, 0x15, 0x4b, 0x9e,
	0x39, 0x13, 0x1d, 0x3e, 0x72, 0xf0, 0x0d, 0xcd, 0xd7, 0xea, 0x17, 0x7b, 0x65, 0x9d, 0xb2, 0x5a,
	0xfd, 0x3c, 0xf9, 0x83, 0x25, 0x7f, 0x96, 0x6b, 0x91, 0x15, 0x82, 0xd5, 0x05, 0xcd, 0x3b, 0x7c,
	0x50, 0xd1, 0xed, 0x5f, 0xac, 0x50, 0x6e, 0xfb, 0x09, 0x15, 0xec, 0xb5, 0xac, 0x33, 0xa6, 0x26,
	0xf3, 0x41, 0xd4, 0xb4, 0xe0, 0x34, 0x11, 0x59, 0x59, 0xa8, 0xf9, 0xd1, 0x9a, 0xd1, 0xe7, 0xa4,
	0xdc, 0xb0, 0x9a, 0xbe, 0x76, 0xd5, 0xbe, 0xfe, 0x77, 0x8a, 0x06, 0xb7, 0x65, 0x42, 0xf3, 0x95,
	0x5c, 0x1b, 0xc7, 0xdf, 0xa1, 0xbd, 0x25, 0x13, 0xf7, 0xdd, 0xda, 0xf0, 0x90, 0x58, 0xa3, 0x07,
	0xf6, 0xf7, 0x9a, 0x71, 0x31, 0xf9, 0xe8, 0x82, 0xbc, 0x2a, 0x0b, 0xce, 0xe6, 0x6f, 0xf0, 0x0d,
	0xda, 0x37, 0xc4, 0x15, 0x13, 0x34, 0xcb, 0xf1, 0x88, 0xf8, 0x90, 0x72, 0x19, 0x03, 0x8c, 0xb6,
	0xba, 0x46, 0xef, 0x0d, 0x7b, 0xdf, 0x74, 0x14, 0x7f, 0x22, 0x1e, 0xa2, 0x8c, 0x46, 0x21, 0xa1,
	0x7d, 0xbe, 0x45, 0x83, 0x25, 0x13, 0x0b, 0xdd, 0x1f, 0x7c, 0x40, 0x9c, 0xb1, 0xf2, 0xd8, 0x23,
	0x06, 0xd3, 0xe5, 0x3b, 0x68, 0xfb, 0x23, 0xad, 0xb8, 0x2c, 0x6f, 0x23, 0x4e, 0x79, 0x97, 0xd0,
	0xe5, 0xef, 0x10, 0x76, 0xc9, 0xcb, 0xed, 0xcd, 0x15, 0x9e, 0x90, 0x00, 0x4c, 0x95, 0xdb, 0x11,
	0xc8, 0x69, 0xc3, 0x5b, 0xf4, 0x61, 0x51, 0x33, 0x2a, 0x98, 0x25, 0xc1, 0x63, 0x12, 0x60, 0xca,
	0x6e, 0x02, 0x51, 0xb6, 0xdb, 0x63, 0x95, 0x06, 0x6e, 0x01, 0x66, 0xdc, 0x00, 0xca, 0x76, 0xbb,
	0x62, 0x39, 0xf3, 0xdd, 0x02, 0xcc, 0xb8, 0x01, 0x94, 0x76, 0x3b, 0x47, 0x9f, 0x2d, 0x99, 0xb8,
	0x6b, 0x4e, 0x03, 0xde, 0x27, 0xea, 0x9f, 0xea, 0xb7, 0x6f, 0x49, 0x3b, 0x9c, 0xbf, 0x69, 0x36,
	0xac, 0x5c, 0xa2, 0x94, 0x0e, 0x89, 0x35, 0x32, 0x1b, 0xd6, 0x01, 0xbd, 0x78, 0xba, 0xad, 0xb3,
	0xaa, 0x58, 0xb2, 0x62, 0x82, 0xcb, 0x78, 0x3c, 0xd0, 0x89, 0x27, 0xe0, 0xb4, 0xe1, 0xcf, 0xe8,
	0x20, 0xe0, 0xdb, 0xc8, 0x4f, 0x08, 0x84, 0xeb, 0xd4, 0x4f, 0x63, 0xb4, 0x76, 0x7e, 0x44, 0x1f,
	0xe5, 0x1a, 0x5c, 0x15, 0x3e, 0x26, 0x10, 0xac, 0x7c, 0x4f, 0x22, 0xac, 0x6d, 0x2b, 0x23, 0x0d,
	0x6c, 0x21, 0xd8, 0xd8, 0xc2, 0xac, 0x6d, 0x2b, 0xb3, 0x0d, 0x6c, 0x21, 0xd8, 0xd8, 0xc2, 0x6c,
	0x6f, 0x7b, 0xdb, 0xc3, 0x09, 0xb4, 0xd7, 0x3e, 0xa2, 0xa7, 0x31, 0x5a, 0x3b, 0x53, 0x34, 0x82,
	0x24, 0x6d, 0x76, 0x33, 0x12, 0xa1, 0x74, 0x7c, 0x67, 0x3d, 0x0a, 0x5d, 0xe2, 0x37, 0xf4, 0x09,
	0x0a, 0xa3, 0x39, 0x24, 0x53, 0x12, 0x61, 0x54, 0x81, 0x59, 0x5c, 0x60, 0xfb, 0x43, 0xa9, 0x48,
	0xff, 0x08, 0x63, 0xfc, 0xa3, 0x02, 0xdb, 0x1f, 0x8a, 0x47, 0xfa, 0x47, 0x18, 0xe3, 0x1f, 0x15,
	0xd8, 0x7b, 0xc6, 0xed, 0xe2, 0x53, 0xf3, 0x59, 0xe4, 0xf8, 0x98, 0x40, 0xb0, 0xd9, 0x33, 0x30,
	0x6b, 0x4f, 0x1b, 0x50, 0xb4, 0xc1, 0x4e, 0x09, 0xcc, 0xa4, 0x66, 0xda, 0x51, 0x81, 0xf6, 0xff,
	0x15, 0x1d, 0x06, 0xd9, 0xb4, 0x3a, 0x7c, 0x4a, 0x60, 0x42, 0xb9, 0x4f, 0xa3, 0xbc, 0x6d, 0x1e,
	0x04, 0xa3, 0xcc, 0x61, 0xc2, 0x98, 0xc7, 0x78, 0xdb, 0x3c, 0x48, 0x45, 0x99, 0xc3, 0x84, 0x31,
	0x8f, 0xf1, 0x3b, 0xda, 0xde, 0x1e, 0x56, 0xb0, 0xed, 0xf6, 0x71, 0x9d, 0xc5, 0x05, 0xda, 0xff,
	0x15, 0x4d, 0x60, 0x51, 0x9b, 0xec, 0x9c, 0x44, 0x49, 0x1d, 0xee, 0xe7, 0xbd, 0x1a, 0x5d, 0x28,
	0x45, 0x63, 0x38, 0xa6, 0x66, 0xe3, 0x9f, 0x91, 0x28, 0xa7, 0xca, 0xcc, 0xfb, 0x24, 0x76, 0x15,
	0x38, 0x2f, 0x59, 0x25, 0xca, 0x99, 0x2a, 0x3d, 0x12, 0xbb, 0x0a, 0x1c, 0x9c, 0xac, 0x12, 0xe5,
	0x4c, 0x95, 0x1e, 0x89, 0xae, 0xf2, 0x03, 0x1a, 0x74, 0x4b, 0x96, 0xb7, 0x54, 0x7c, 0x40, 0x9c,
	0xb1, 0x72, 0x3b, 0xf4, 0x61, 0xed, 0xf0, 0x80, 0x86, 0x0e, 0xd5, 0xdd, 0x25, 0x8f, 0x08, 0x80,
	0x2a, 0xb7, 0x63, 0x98, 0xd4, 0x9e, 0xdf, 0xa3, 0x77, 0x4d, 0xde, 0x1d, 0x4b, 0x05, 0xc5, 0x98,
	0x18, 0x40, 0xb9, 0x0c, 0x1d, 0xcc, 0xbf, 0xd9, 0x3a, 0xb3, 0x19, 0x11, 0x1f, 0x72, 0x6f, 0xb6,
	0x91, 0x79, 0xac, 0xd0, 0xd8, 0x67, 0x2f, 0xb7, 0xaa, 0x53, 0x71, 0xcf, 0x49, 0xc0, 0x70, 0xe8,
	0x22, 0x67, 0xaf, 0x4f, 0x5d, 0xe4, 0x2c, 0xcc, 0xbf, 0xc8, 0x39, 0x94, 0xdd, 0x7e, 0x97, 0x56,
	0xed, 0x07, 0x50, 0xd3, 0x7e, 0x90, 0xb4, 0x67, 0xb8, 0x64, 0xe2, 0xa7, 0x7f, 0xae, 0xd7, 0xf9,
	0xef, 0x59, 0x9e, 0x37, 0x1a, 0x8e, 0xdb, 0x46, 0xb9, 0x98, 0xb3, 0x5e, 0x9f, 0xf2, 0xbe, 0x15,
	0x0e, 0xdd, 0x1c, 0x5b, 0xf9, 0xad, 0x08, 0x60, 0xe7, 0x5b, 0x01, 0xb0, 0xe1, 0xbe, 0x73, 0x44,
	0x7a, 0xdf, 0x39, 0xa8, 0xbf, 0xef, 0x3c, 0x32, 0x6c, 0xa6, 0xef, 0x09, 0xa0, 0x7e, 0x33, 0x63,
	0x9e, 0x15, 0x3a, 0x59, 0x32, 0xf1, 0xc4, 0x8a, 0xb4, 0xac, 0x57, 0xeb, 0x97, 0xaa, 0x2e, 0x37,
	0x59, 0x91, 0xb0, 0x45, 0xf7, 0xb8, 0xe3, 0xf8, 0x0b, 0xd2, 0xcb, 0xab, 0x3a, 0xe7, 0xbb, 0x64,
	0xba, 0xe2, 0x16, 0xcd, 0xfa, 0xa4, 0xed, 0x7f, 0xba, 0x17, 0x64, 0x87, 0x44, 0x07, 0xf1, 0xd5,
	0xff, 0x50, 0xea, 0xd2, 0x1b, 0x34, 0x95, 0x1d, 0x8e, 0xfe, 0x00, 0x7f, 0x49, 0x76, 0x28, 0x54,
	0xe1, 0x8b, 0xdd, 0x42, 0xbb, 0xae, 0x4c, 0xa1, 0xaf, 0xee, 0x0e, 0x85, 0xa9, 0xbb, 0x53, 0x68,
	0x3f, 0x4a, 0x16, 0xdd, 0xb3, 0xff, 0x89, 0xe6, 0x59, 0x4a, 0x9b, 0x47, 0x3c, 0x9e, 0x90, 0x10,
	0x34, 0x8f, 0x12, 0x88, 0x53, 0x86, 0x97, 0xef, 0x7f, 0x19, 0xe4, 0xcd, 0x1b, 0xbf, 0xfb, 0xfb,
	0x05, 0x7f, 0x79, 0xdb, 0x3e, 0xfe, 0xbf, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x9c, 0xa0,
	0xf7, 0xd2, 0x10, 0x00, 0x00,
}
