// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetProductDetailRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductDetailRequest) Reset()         { *m = GetProductDetailRequest{} }
func (m *GetProductDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductDetailRequest) ProtoMessage()    {}
func (*GetProductDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_052f26a89e0c1fa2, []int{0}
}
func (m *GetProductDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductDetailRequest.Unmarshal(m, b)
}
func (m *GetProductDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductDetailRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductDetailRequest.Merge(dst, src)
}
func (m *GetProductDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductDetailRequest.Size(m)
}
func (m *GetProductDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductDetailRequest proto.InternalMessageInfo

func (m *GetProductDetailRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetProductDetailResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductDetailResponse) Reset()         { *m = GetProductDetailResponse{} }
func (m *GetProductDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductDetailResponse) ProtoMessage()    {}
func (*GetProductDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_052f26a89e0c1fa2, []int{1}
}
func (m *GetProductDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductDetailResponse.Unmarshal(m, b)
}
func (m *GetProductDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductDetailResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductDetailResponse.Merge(dst, src)
}
func (m *GetProductDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductDetailResponse.Size(m)
}
func (m *GetProductDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductDetailResponse proto.InternalMessageInfo

func (m *GetProductDetailResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductsRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsRequest) Reset()         { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()    {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_052f26a89e0c1fa2, []int{2}
}
func (m *GetProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsRequest.Unmarshal(m, b)
}
func (m *GetProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsRequest.Merge(dst, src)
}
func (m *GetProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsRequest.Size(m)
}
func (m *GetProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsRequest proto.InternalMessageInfo

func (m *GetProductsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetProductsResponse struct {
	Products             *Products `protobuf:"bytes,1,opt,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetProductsResponse) Reset()         { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()    {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_052f26a89e0c1fa2, []int{3}
}
func (m *GetProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsResponse.Unmarshal(m, b)
}
func (m *GetProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsResponse.Merge(dst, src)
}
func (m *GetProductsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsResponse.Size(m)
}
func (m *GetProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsResponse proto.InternalMessageInfo

func (m *GetProductsResponse) GetProducts() *Products {
	if m != nil {
		return m.Products
	}
	return nil
}

type Product struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VendorId             int64                `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	CategoryId           int64                `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ProductName          string               `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductDescription   string               `protobuf:"bytes,5,opt,name=product_description,json=productDescription,proto3" json:"product_description,omitempty"`
	ProductStatus        int32                `protobuf:"varint,6,opt,name=product_status,json=productStatus,proto3" json:"product_status,omitempty"`
	ProductCreatedTime   *timestamp.Timestamp `protobuf:"bytes,7,opt,name=product_created_time,json=productCreatedTime,proto3" json:"product_created_time,omitempty"`
	ProductUpdatedTime   *timestamp.Timestamp `protobuf:"bytes,8,opt,name=product_updated_time,json=productUpdatedTime,proto3" json:"product_updated_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_052f26a89e0c1fa2, []int{4}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetVendorId() int64 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *Product) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Product) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Product) GetProductDescription() string {
	if m != nil {
		return m.ProductDescription
	}
	return ""
}

func (m *Product) GetProductStatus() int32 {
	if m != nil {
		return m.ProductStatus
	}
	return 0
}

func (m *Product) GetProductCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.ProductCreatedTime
	}
	return nil
}

func (m *Product) GetProductUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.ProductUpdatedTime
	}
	return nil
}

type Products struct {
	Product              []*Product `protobuf:"bytes,1,rep,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Products) Reset()         { *m = Products{} }
func (m *Products) String() string { return proto.CompactTextString(m) }
func (*Products) ProtoMessage()    {}
func (*Products) Descriptor() ([]byte, []int) {
	return fileDescriptor_products_052f26a89e0c1fa2, []int{5}
}
func (m *Products) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Products.Unmarshal(m, b)
}
func (m *Products) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Products.Marshal(b, m, deterministic)
}
func (dst *Products) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Products.Merge(dst, src)
}
func (m *Products) XXX_Size() int {
	return xxx_messageInfo_Products.Size(m)
}
func (m *Products) XXX_DiscardUnknown() {
	xxx_messageInfo_Products.DiscardUnknown(m)
}

var xxx_messageInfo_Products proto.InternalMessageInfo

func (m *Products) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProductDetailRequest)(nil), "protos.GetProductDetailRequest")
	proto.RegisterType((*GetProductDetailResponse)(nil), "protos.GetProductDetailResponse")
	proto.RegisterType((*GetProductsRequest)(nil), "protos.GetProductsRequest")
	proto.RegisterType((*GetProductsResponse)(nil), "protos.GetProductsResponse")
	proto.RegisterType((*Product)(nil), "protos.Product")
	proto.RegisterType((*Products)(nil), "protos.Products")
}

func init() { proto.RegisterFile("products.proto", fileDescriptor_products_052f26a89e0c1fa2) }

var fileDescriptor_products_052f26a89e0c1fa2 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xed, 0x4a, 0xe3, 0x40,
	0x14, 0x25, 0xe9, 0xb6, 0x4d, 0x6f, 0x77, 0xbb, 0xcb, 0xb4, 0xb0, 0xa1, 0xfe, 0x68, 0x0d, 0x08,
	0xad, 0x48, 0x0a, 0x8a, 0x4f, 0x50, 0x45, 0x0a, 0x22, 0x12, 0xf5, 0x77, 0x48, 0x33, 0xd7, 0x32,
	0xd0, 0x64, 0x62, 0x66, 0x22, 0xf8, 0xd2, 0x3e, 0x83, 0x64, 0x3e, 0x52, 0x5b, 0x41, 0xfc, 0x15,
	0xe6, 0x9c, 0x73, 0xcf, 0xc9, 0xcc, 0xb9, 0x30, 0x28, 0x4a, 0x4e, 0xab, 0x54, 0x8a, 0xb0, 0x28,
	0xb9, 0xe4, 0xa4, 0xa3, 0x3e, 0x62, 0x3c, 0xd9, 0x70, 0xbe, 0xd9, 0xe2, 0x42, 0x1d, 0xd7, 0xd5,
	0xf3, 0x42, 0xb2, 0x0c, 0x85, 0x4c, 0xb2, 0x42, 0x0b, 0x83, 0x39, 0xfc, 0xbf, 0x41, 0x79, 0xaf,
	0xa7, 0xaf, 0x50, 0x26, 0x6c, 0x1b, 0xe1, 0x4b, 0x85, 0x42, 0x92, 0x01, 0xb8, 0x8c, 0xfa, 0xce,
	0xd4, 0x99, 0xb5, 0x22, 0x97, 0xd1, 0xe0, 0x1a, 0xfc, 0xaf, 0x52, 0x51, 0xf0, 0x5c, 0x20, 0x99,
	0x43, 0xd7, 0xfc, 0x81, 0x1a, 0xe8, 0x9f, 0xff, 0xd5, 0xfe, 0x22, 0x34, 0xfa, 0xc8, 0xf2, 0xc1,
	0x29, 0x90, 0x9d, 0x8d, 0xb0, 0x61, 0x23, 0x68, 0x6f, 0x59, 0xc6, 0xa4, 0xc9, 0xd3, 0x87, 0x60,
	0x09, 0xc3, 0x3d, 0xad, 0x49, 0x3b, 0x03, 0xcf, 0xde, 0xd7, 0xc4, 0xfd, 0x3b, 0x88, 0x13, 0x51,
	0xa3, 0x08, 0xde, 0x5d, 0xe8, 0x1a, 0xf8, 0xf0, 0x4e, 0xe4, 0x08, 0x7a, 0xaf, 0x98, 0x53, 0x5e,
	0xc6, 0x8c, 0xfa, 0xae, 0x82, 0x3d, 0x0d, 0xac, 0x28, 0x99, 0x40, 0x3f, 0x4d, 0x24, 0x6e, 0x78,
	0xf9, 0x56, 0xd3, 0x2d, 0x45, 0x83, 0x85, 0x56, 0x94, 0x1c, 0xc3, 0x6f, 0x93, 0x12, 0xe7, 0x49,
	0x86, 0xfe, 0xaf, 0xa9, 0x33, 0xeb, 0x45, 0x7d, 0x83, 0xdd, 0x25, 0x19, 0x92, 0x05, 0x0c, 0xad,
	0x84, 0xa2, 0x48, 0x4b, 0x56, 0x48, 0xc6, 0x73, 0xbf, 0xad, 0x94, 0xa4, 0xb0, 0x8f, 0xd9, 0x30,
	0xe4, 0xa4, 0xe9, 0x32, 0x16, 0x32, 0x91, 0x95, 0xf0, 0x3b, 0x53, 0x67, 0xd6, 0x8e, 0xfe, 0x18,
	0xf4, 0x41, 0x81, 0xe4, 0x16, 0x46, 0x56, 0x96, 0x96, 0x98, 0x48, 0xa4, 0x71, 0x5d, 0xad, 0xdf,
	0x55, 0xcf, 0x31, 0x0e, 0x75, 0xef, 0xa1, 0xed, 0x3d, 0x7c, 0xb4, 0xbd, 0x37, 0xa1, 0x4b, 0x3d,
	0x56, 0x13, 0x9f, 0xdd, 0xaa, 0x82, 0xee, 0xdc, 0xbc, 0x1f, 0xbb, 0x3d, 0xe9, 0xb1, 0x9a, 0x08,
	0x2e, 0xc1, 0xb3, 0x35, 0xec, 0x2f, 0x46, 0xeb, 0xbb, 0xc5, 0x58, 0xeb, 0x9d, 0xbd, 0xf8, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x26, 0x8e, 0x14, 0x00, 0xcc, 0x02, 0x00, 0x00,
}
