// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agg_map_location.proto

package localservices

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AggMapLocation struct {
	AggDistrictId        int64    `protobuf:"varint,1,opt,name=agg_district_id,json=aggDistrictId,proto3" json:"agg_district_id,omitempty"`
	SubDistrictId        int64    `protobuf:"varint,2,opt,name=sub_district_id,json=subDistrictId,proto3" json:"sub_district_id,omitempty"`
	AggregatorId         int64    `protobuf:"varint,3,opt,name=aggregator_id,json=aggregatorId,proto3" json:"aggregator_id,omitempty"`
	AggDistrictName      string   `protobuf:"bytes,4,opt,name=agg_district_name,json=aggDistrictName,proto3" json:"agg_district_name,omitempty"`
	IsActive             bool     `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggMapLocation) Reset()         { *m = AggMapLocation{} }
func (m *AggMapLocation) String() string { return proto.CompactTextString(m) }
func (*AggMapLocation) ProtoMessage()    {}
func (*AggMapLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_agg_map_location_92b65668a4751536, []int{0}
}
func (m *AggMapLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggMapLocation.Unmarshal(m, b)
}
func (m *AggMapLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggMapLocation.Marshal(b, m, deterministic)
}
func (dst *AggMapLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggMapLocation.Merge(dst, src)
}
func (m *AggMapLocation) XXX_Size() int {
	return xxx_messageInfo_AggMapLocation.Size(m)
}
func (m *AggMapLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_AggMapLocation.DiscardUnknown(m)
}

var xxx_messageInfo_AggMapLocation proto.InternalMessageInfo

func (m *AggMapLocation) GetAggDistrictId() int64 {
	if m != nil {
		return m.AggDistrictId
	}
	return 0
}

func (m *AggMapLocation) GetSubDistrictId() int64 {
	if m != nil {
		return m.SubDistrictId
	}
	return 0
}

func (m *AggMapLocation) GetAggregatorId() int64 {
	if m != nil {
		return m.AggregatorId
	}
	return 0
}

func (m *AggMapLocation) GetAggDistrictName() string {
	if m != nil {
		return m.AggDistrictName
	}
	return ""
}

func (m *AggMapLocation) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type CreateAggMapLocationRequest struct {
	AggMapLocation       *AggMapLocation `protobuf:"bytes,1,opt,name=agg_map_location,json=aggMapLocation,proto3" json:"agg_map_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateAggMapLocationRequest) Reset()         { *m = CreateAggMapLocationRequest{} }
func (m *CreateAggMapLocationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAggMapLocationRequest) ProtoMessage()    {}
func (*CreateAggMapLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agg_map_location_92b65668a4751536, []int{1}
}
func (m *CreateAggMapLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAggMapLocationRequest.Unmarshal(m, b)
}
func (m *CreateAggMapLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAggMapLocationRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAggMapLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAggMapLocationRequest.Merge(dst, src)
}
func (m *CreateAggMapLocationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAggMapLocationRequest.Size(m)
}
func (m *CreateAggMapLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAggMapLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAggMapLocationRequest proto.InternalMessageInfo

func (m *CreateAggMapLocationRequest) GetAggMapLocation() *AggMapLocation {
	if m != nil {
		return m.AggMapLocation
	}
	return nil
}

type CreateAggMapLocationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAggMapLocationResponse) Reset()         { *m = CreateAggMapLocationResponse{} }
func (m *CreateAggMapLocationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAggMapLocationResponse) ProtoMessage()    {}
func (*CreateAggMapLocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agg_map_location_92b65668a4751536, []int{2}
}
func (m *CreateAggMapLocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAggMapLocationResponse.Unmarshal(m, b)
}
func (m *CreateAggMapLocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAggMapLocationResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAggMapLocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAggMapLocationResponse.Merge(dst, src)
}
func (m *CreateAggMapLocationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAggMapLocationResponse.Size(m)
}
func (m *CreateAggMapLocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAggMapLocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAggMapLocationResponse proto.InternalMessageInfo

type GetAggMapLocationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAggMapLocationsRequest) Reset()         { *m = GetAggMapLocationsRequest{} }
func (m *GetAggMapLocationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAggMapLocationsRequest) ProtoMessage()    {}
func (*GetAggMapLocationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agg_map_location_92b65668a4751536, []int{3}
}
func (m *GetAggMapLocationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAggMapLocationsRequest.Unmarshal(m, b)
}
func (m *GetAggMapLocationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAggMapLocationsRequest.Marshal(b, m, deterministic)
}
func (dst *GetAggMapLocationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAggMapLocationsRequest.Merge(dst, src)
}
func (m *GetAggMapLocationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAggMapLocationsRequest.Size(m)
}
func (m *GetAggMapLocationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAggMapLocationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAggMapLocationsRequest proto.InternalMessageInfo

type GetAggMapLocationsResponse struct {
	AggMapLocation       []*AggMapLocation `protobuf:"bytes,1,rep,name=agg_map_location,json=aggMapLocation,proto3" json:"agg_map_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAggMapLocationsResponse) Reset()         { *m = GetAggMapLocationsResponse{} }
func (m *GetAggMapLocationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAggMapLocationsResponse) ProtoMessage()    {}
func (*GetAggMapLocationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agg_map_location_92b65668a4751536, []int{4}
}
func (m *GetAggMapLocationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAggMapLocationsResponse.Unmarshal(m, b)
}
func (m *GetAggMapLocationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAggMapLocationsResponse.Marshal(b, m, deterministic)
}
func (dst *GetAggMapLocationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAggMapLocationsResponse.Merge(dst, src)
}
func (m *GetAggMapLocationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAggMapLocationsResponse.Size(m)
}
func (m *GetAggMapLocationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAggMapLocationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAggMapLocationsResponse proto.InternalMessageInfo

func (m *GetAggMapLocationsResponse) GetAggMapLocation() []*AggMapLocation {
	if m != nil {
		return m.AggMapLocation
	}
	return nil
}

type UpdateAggMapLocationRequest struct {
	AggMapLocation       *AggMapLocation `protobuf:"bytes,1,opt,name=agg_map_location,json=aggMapLocation,proto3" json:"agg_map_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateAggMapLocationRequest) Reset()         { *m = UpdateAggMapLocationRequest{} }
func (m *UpdateAggMapLocationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAggMapLocationRequest) ProtoMessage()    {}
func (*UpdateAggMapLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agg_map_location_92b65668a4751536, []int{5}
}
func (m *UpdateAggMapLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAggMapLocationRequest.Unmarshal(m, b)
}
func (m *UpdateAggMapLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAggMapLocationRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAggMapLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAggMapLocationRequest.Merge(dst, src)
}
func (m *UpdateAggMapLocationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAggMapLocationRequest.Size(m)
}
func (m *UpdateAggMapLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAggMapLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAggMapLocationRequest proto.InternalMessageInfo

func (m *UpdateAggMapLocationRequest) GetAggMapLocation() *AggMapLocation {
	if m != nil {
		return m.AggMapLocation
	}
	return nil
}

type UpdateAggMapLocationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAggMapLocationResponse) Reset()         { *m = UpdateAggMapLocationResponse{} }
func (m *UpdateAggMapLocationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAggMapLocationResponse) ProtoMessage()    {}
func (*UpdateAggMapLocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agg_map_location_92b65668a4751536, []int{6}
}
func (m *UpdateAggMapLocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAggMapLocationResponse.Unmarshal(m, b)
}
func (m *UpdateAggMapLocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAggMapLocationResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateAggMapLocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAggMapLocationResponse.Merge(dst, src)
}
func (m *UpdateAggMapLocationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAggMapLocationResponse.Size(m)
}
func (m *UpdateAggMapLocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAggMapLocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAggMapLocationResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AggMapLocation)(nil), "AggMapLocation")
	proto.RegisterType((*CreateAggMapLocationRequest)(nil), "CreateAggMapLocationRequest")
	proto.RegisterType((*CreateAggMapLocationResponse)(nil), "CreateAggMapLocationResponse")
	proto.RegisterType((*GetAggMapLocationsRequest)(nil), "GetAggMapLocationsRequest")
	proto.RegisterType((*GetAggMapLocationsResponse)(nil), "GetAggMapLocationsResponse")
	proto.RegisterType((*UpdateAggMapLocationRequest)(nil), "UpdateAggMapLocationRequest")
	proto.RegisterType((*UpdateAggMapLocationResponse)(nil), "UpdateAggMapLocationResponse")
}

func init() {
	proto.RegisterFile("agg_map_location.proto", fileDescriptor_agg_map_location_92b65668a4751536)
}

var fileDescriptor_agg_map_location_92b65668a4751536 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x55, 0x69, 0x47, 0xdb, 0x68, 0x0e, 0x52, 0x8d, 0x48, 0x88, 0x20, 0xc1, 0x43,
	0x0f, 0x7a, 0xf2, 0x58, 0x15, 0xa4, 0xa0, 0x1e, 0x02, 0x62, 0xf1, 0x12, 0x26, 0xc9, 0xb0, 0x2c,
	0x34, 0xd9, 0xb8, 0xb3, 0xe9, 0xc7, 0xf4, 0x33, 0x49, 0xfe, 0x80, 0x4d, 0x89, 0xe0, 0xc5, 0xe3,
	0xcc, 0xfc, 0x66, 0xde, 0x7b, 0xcb, 0xc2, 0x09, 0x0a, 0x11, 0x65, 0x58, 0x44, 0x2b, 0x95, 0xa0,
	0x91, 0x2a, 0x9f, 0x15, 0x5a, 0x19, 0xe5, 0x7f, 0x59, 0x30, 0x99, 0x0b, 0xf1, 0x82, 0xc5, 0x73,
	0x3b, 0x70, 0xae, 0xc0, 0xae, 0xe0, 0x54, 0xb2, 0xd1, 0x32, 0x31, 0x91, 0x4c, 0xa7, 0x96, 0x67,
	0x05, 0x83, 0x70, 0x8c, 0x42, 0x3c, 0xb6, 0xdd, 0x45, 0x5a, 0x71, 0x5c, 0xc6, 0x1d, 0x6e, 0xa7,
	0xe1, 0xb8, 0x8c, 0x37, 0xb8, 0x4b, 0xa8, 0x16, 0x35, 0x09, 0x34, 0x4a, 0x57, 0xd4, 0xa0, 0xa6,
	0x0e, 0x7f, 0x9a, 0x8b, 0xd4, 0xb9, 0x86, 0xe3, 0x8e, 0x68, 0x8e, 0x19, 0x4d, 0x77, 0x3d, 0x2b,
	0x18, 0x85, 0xf6, 0x86, 0xec, 0x2b, 0x66, 0xe4, 0xb8, 0x30, 0x92, 0x1c, 0x61, 0x62, 0xe4, 0x9a,
	0xa6, 0x7b, 0x9e, 0x15, 0x0c, 0xc3, 0xa1, 0xe4, 0x79, 0x5d, 0xfb, 0x4b, 0x70, 0x1f, 0x34, 0xa1,
	0xa1, 0x6e, 0xaa, 0x90, 0x3e, 0x4b, 0x62, 0xe3, 0xdc, 0xc1, 0xd1, 0xf6, 0x4b, 0xd4, 0xe9, 0x0e,
	0x6e, 0xec, 0xd9, 0xd6, 0xc6, 0x04, 0x3b, 0xb5, 0x7f, 0x01, 0xe7, 0xfd, 0x97, 0xb9, 0x50, 0x39,
	0x93, 0xef, 0xc2, 0xe9, 0x13, 0x99, 0xee, 0x90, 0x5b, 0x5d, 0xff, 0x1d, 0xce, 0xfa, 0x86, 0xcd,
	0xea, 0x2f, 0xae, 0x06, 0x7f, 0x71, 0xb5, 0x04, 0xf7, 0xad, 0x48, 0xff, 0x29, 0x6f, 0xff, 0xe5,
	0xc6, 0xf4, 0xbd, 0xfd, 0x31, 0xae, 0x4e, 0xae, 0x98, 0xf4, 0x5a, 0x26, 0xc4, 0xf1, 0x7e, 0xfd,
	0xa5, 0x6e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x06, 0xa0, 0x7f, 0x86, 0x6c, 0x02, 0x00, 0x00,
}
