// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkoutinternal.proto

package localservices

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckoutValidationRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Metadata             string   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutValidationRequest) Reset()         { *m = CheckoutValidationRequest{} }
func (m *CheckoutValidationRequest) String() string { return proto.CompactTextString(m) }
func (*CheckoutValidationRequest) ProtoMessage()    {}
func (*CheckoutValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_a720ff68e5cf42ed, []int{0}
}
func (m *CheckoutValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutValidationRequest.Unmarshal(m, b)
}
func (m *CheckoutValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutValidationRequest.Marshal(b, m, deterministic)
}
func (dst *CheckoutValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutValidationRequest.Merge(dst, src)
}
func (m *CheckoutValidationRequest) XXX_Size() int {
	return xxx_messageInfo_CheckoutValidationRequest.Size(m)
}
func (m *CheckoutValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutValidationRequest proto.InternalMessageInfo

func (m *CheckoutValidationRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CheckoutValidationRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type CheckoutValidationResponse struct {
	Metadata             string   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Transaction          *TxCI    `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutValidationResponse) Reset()         { *m = CheckoutValidationResponse{} }
func (m *CheckoutValidationResponse) String() string { return proto.CompactTextString(m) }
func (*CheckoutValidationResponse) ProtoMessage()    {}
func (*CheckoutValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_a720ff68e5cf42ed, []int{1}
}
func (m *CheckoutValidationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutValidationResponse.Unmarshal(m, b)
}
func (m *CheckoutValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutValidationResponse.Marshal(b, m, deterministic)
}
func (dst *CheckoutValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutValidationResponse.Merge(dst, src)
}
func (m *CheckoutValidationResponse) XXX_Size() int {
	return xxx_messageInfo_CheckoutValidationResponse.Size(m)
}
func (m *CheckoutValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutValidationResponse proto.InternalMessageInfo

func (m *CheckoutValidationResponse) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *CheckoutValidationResponse) GetTransaction() *TxCI {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type TxCI struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TotalTransaction     int64          `protobuf:"varint,2,opt,name=total_transaction,json=totalTransaction,proto3" json:"total_transaction,omitempty"`
	Orders               []*OrderInfoCI `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TxCI) Reset()         { *m = TxCI{} }
func (m *TxCI) String() string { return proto.CompactTextString(m) }
func (*TxCI) ProtoMessage()    {}
func (*TxCI) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_a720ff68e5cf42ed, []int{2}
}
func (m *TxCI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxCI.Unmarshal(m, b)
}
func (m *TxCI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxCI.Marshal(b, m, deterministic)
}
func (dst *TxCI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxCI.Merge(dst, src)
}
func (m *TxCI) XXX_Size() int {
	return xxx_messageInfo_TxCI.Size(m)
}
func (m *TxCI) XXX_DiscardUnknown() {
	xxx_messageInfo_TxCI.DiscardUnknown(m)
}

var xxx_messageInfo_TxCI proto.InternalMessageInfo

func (m *TxCI) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TxCI) GetTotalTransaction() int64 {
	if m != nil {
		return m.TotalTransaction
	}
	return 0
}

func (m *TxCI) GetOrders() []*OrderInfoCI {
	if m != nil {
		return m.Orders
	}
	return nil
}

type OrderInfoCI struct {
	TotalAmount          int64           `protobuf:"varint,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Address              string          `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Shipping             *ShippingInfoCI `protobuf:"bytes,3,opt,name=shipping,proto3" json:"shipping,omitempty"`
	Details              []*DetailInfoCI `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OrderInfoCI) Reset()         { *m = OrderInfoCI{} }
func (m *OrderInfoCI) String() string { return proto.CompactTextString(m) }
func (*OrderInfoCI) ProtoMessage()    {}
func (*OrderInfoCI) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_a720ff68e5cf42ed, []int{3}
}
func (m *OrderInfoCI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfoCI.Unmarshal(m, b)
}
func (m *OrderInfoCI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfoCI.Marshal(b, m, deterministic)
}
func (dst *OrderInfoCI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfoCI.Merge(dst, src)
}
func (m *OrderInfoCI) XXX_Size() int {
	return xxx_messageInfo_OrderInfoCI.Size(m)
}
func (m *OrderInfoCI) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfoCI.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfoCI proto.InternalMessageInfo

func (m *OrderInfoCI) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *OrderInfoCI) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OrderInfoCI) GetShipping() *ShippingInfoCI {
	if m != nil {
		return m.Shipping
	}
	return nil
}

func (m *OrderInfoCI) GetDetails() []*DetailInfoCI {
	if m != nil {
		return m.Details
	}
	return nil
}

type ShippingInfoCI struct {
	ShippingName         string   `protobuf:"bytes,1,opt,name=shipping_name,json=shippingName,proto3" json:"shipping_name,omitempty"`
	ShippingFee          int64    `protobuf:"varint,2,opt,name=shipping_fee,json=shippingFee,proto3" json:"shipping_fee,omitempty"`
	ShippingInsuranceFee int64    `protobuf:"varint,3,opt,name=shipping_insurance_fee,json=shippingInsuranceFee,proto3" json:"shipping_insurance_fee,omitempty"`
	ShipperName          string   `protobuf:"bytes,4,opt,name=shipper_name,json=shipperName,proto3" json:"shipper_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShippingInfoCI) Reset()         { *m = ShippingInfoCI{} }
func (m *ShippingInfoCI) String() string { return proto.CompactTextString(m) }
func (*ShippingInfoCI) ProtoMessage()    {}
func (*ShippingInfoCI) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_a720ff68e5cf42ed, []int{4}
}
func (m *ShippingInfoCI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShippingInfoCI.Unmarshal(m, b)
}
func (m *ShippingInfoCI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShippingInfoCI.Marshal(b, m, deterministic)
}
func (dst *ShippingInfoCI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShippingInfoCI.Merge(dst, src)
}
func (m *ShippingInfoCI) XXX_Size() int {
	return xxx_messageInfo_ShippingInfoCI.Size(m)
}
func (m *ShippingInfoCI) XXX_DiscardUnknown() {
	xxx_messageInfo_ShippingInfoCI.DiscardUnknown(m)
}

var xxx_messageInfo_ShippingInfoCI proto.InternalMessageInfo

func (m *ShippingInfoCI) GetShippingName() string {
	if m != nil {
		return m.ShippingName
	}
	return ""
}

func (m *ShippingInfoCI) GetShippingFee() int64 {
	if m != nil {
		return m.ShippingFee
	}
	return 0
}

func (m *ShippingInfoCI) GetShippingInsuranceFee() int64 {
	if m != nil {
		return m.ShippingInsuranceFee
	}
	return 0
}

func (m *ShippingInfoCI) GetShipperName() string {
	if m != nil {
		return m.ShipperName
	}
	return ""
}

type DetailInfoCI struct {
	ProductName          string   `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductPrice         int64    `protobuf:"varint,2,opt,name=product_price,json=productPrice,proto3" json:"product_price,omitempty"`
	Quantity             int64    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Subtotal             int64    `protobuf:"varint,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailInfoCI) Reset()         { *m = DetailInfoCI{} }
func (m *DetailInfoCI) String() string { return proto.CompactTextString(m) }
func (*DetailInfoCI) ProtoMessage()    {}
func (*DetailInfoCI) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_a720ff68e5cf42ed, []int{5}
}
func (m *DetailInfoCI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailInfoCI.Unmarshal(m, b)
}
func (m *DetailInfoCI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailInfoCI.Marshal(b, m, deterministic)
}
func (dst *DetailInfoCI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailInfoCI.Merge(dst, src)
}
func (m *DetailInfoCI) XXX_Size() int {
	return xxx_messageInfo_DetailInfoCI.Size(m)
}
func (m *DetailInfoCI) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailInfoCI.DiscardUnknown(m)
}

var xxx_messageInfo_DetailInfoCI proto.InternalMessageInfo

func (m *DetailInfoCI) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *DetailInfoCI) GetProductPrice() int64 {
	if m != nil {
		return m.ProductPrice
	}
	return 0
}

func (m *DetailInfoCI) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *DetailInfoCI) GetSubtotal() int64 {
	if m != nil {
		return m.Subtotal
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckoutValidationRequest)(nil), "CheckoutValidationRequest")
	proto.RegisterType((*CheckoutValidationResponse)(nil), "CheckoutValidationResponse")
	proto.RegisterType((*TxCI)(nil), "TxCI")
	proto.RegisterType((*OrderInfoCI)(nil), "OrderInfoCI")
	proto.RegisterType((*ShippingInfoCI)(nil), "ShippingInfoCI")
	proto.RegisterType((*DetailInfoCI)(nil), "DetailInfoCI")
}

func init() {
	proto.RegisterFile("checkoutinternal.proto", fileDescriptor_checkoutinternal_a720ff68e5cf42ed)
}

var fileDescriptor_checkoutinternal_a720ff68e5cf42ed = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0x9a, 0xd2, 0x8e, 0x93, 0x76, 0x03, 0x0b, 0x8d, 0xb0, 0xab, 0x92, 0x21, 0xad, 0xd2,
	0xa4, 0x5c, 0x0c, 0x5e, 0x00, 0x8a, 0x90, 0x7a, 0x03, 0x53, 0x98, 0xb8, 0xe0, 0xa6, 0x3a, 0x8b,
	0xcf, 0x98, 0x45, 0x6a, 0x67, 0xb6, 0x83, 0xe0, 0x25, 0x78, 0x06, 0x5e, 0x81, 0x37, 0x44, 0xf6,
	0x6c, 0xd3, 0x22, 0x2e, 0xbf, 0x9f, 0x73, 0xbe, 0xcf, 0xa7, 0x0d, 0x1c, 0xb7, 0xb7, 0xd4, 0x7e,
	0x55, 0x83, 0x15, 0xd2, 0x92, 0x96, 0xd8, 0xd5, 0xbd, 0x56, 0x56, 0x55, 0x97, 0xf0, 0x6c, 0x15,
	0x94, 0x4f, 0xd8, 0x09, 0x8e, 0x56, 0x28, 0xd9, 0xd0, 0xdd, 0x40, 0xc6, 0xb2, 0xa7, 0x30, 0x1d,
	0x0c, 0xe9, 0x8d, 0xe0, 0x65, 0xb6, 0xc8, 0x96, 0x79, 0x33, 0x71, 0x70, 0xcd, 0xd9, 0x09, 0x1c,
	0x6c, 0xc9, 0x22, 0x47, 0x8b, 0xe5, 0x68, 0x91, 0x2d, 0x1f, 0x36, 0x09, 0x57, 0x08, 0x27, 0xff,
	0xdb, 0x68, 0x7a, 0x25, 0x0d, 0xed, 0x4d, 0x66, 0xfb, 0x93, 0xec, 0x0c, 0x0a, 0xab, 0x51, 0x1a,
	0x6c, 0xdd, 0x88, 0x5f, 0x5c, 0x5c, 0x3c, 0xa8, 0xaf, 0xbe, 0xaf, 0xd6, 0xcd, 0xae, 0x52, 0x09,
	0x18, 0x3b, 0x92, 0x1d, 0xc2, 0x28, 0x55, 0x1b, 0x09, 0xce, 0xce, 0xe1, 0xb1, 0x55, 0x16, 0xbb,
	0xcd, 0xbf, 0x6b, 0xf2, 0xe6, 0x91, 0x17, 0xae, 0xfe, 0xf2, 0xec, 0x05, 0x4c, 0x94, 0xe6, 0xa4,
	0x4d, 0x99, 0x2f, 0xf2, 0x65, 0x71, 0x31, 0xab, 0x3f, 0x38, 0xb8, 0x96, 0x37, 0x6a, 0xb5, 0x6e,
	0x82, 0x56, 0xfd, 0xca, 0xa0, 0xd8, 0xe1, 0xd9, 0x73, 0x98, 0xdd, 0x47, 0xe0, 0x56, 0x0d, 0xd2,
	0x86, 0xf0, 0xc2, 0x73, 0xaf, 0x3d, 0xc5, 0x4a, 0x98, 0x22, 0xe7, 0x9a, 0x8c, 0x09, 0xb7, 0x89,
	0x90, 0x9d, 0xc3, 0x81, 0xb9, 0x15, 0x7d, 0x2f, 0xe4, 0x97, 0x32, 0xf7, 0xaf, 0x3b, 0xaa, 0x3f,
	0x06, 0x22, 0xe4, 0x26, 0x03, 0x3b, 0x83, 0x29, 0x27, 0x8b, 0xa2, 0x33, 0xe5, 0xd8, 0x17, 0x9c,
	0xd7, 0x6f, 0x3d, 0x0e, 0xce, 0xa8, 0x56, 0xbf, 0x33, 0x38, 0xdc, 0xdf, 0xc2, 0x4e, 0x61, 0x1e,
	0xf7, 0x6c, 0x24, 0x6e, 0x29, 0x9c, 0x7a, 0x16, 0xc9, 0xf7, 0xb8, 0x25, 0xf7, 0x94, 0x64, 0xba,
	0x21, 0x0a, 0x87, 0x2a, 0x22, 0xf7, 0x8e, 0x88, 0xbd, 0x82, 0xe3, 0x64, 0x11, 0xd2, 0x0c, 0x1a,
	0x65, 0x4b, 0xde, 0x9c, 0x7b, 0xf3, 0x13, 0x93, 0x72, 0x83, 0xe8, 0xa6, 0xe2, 0x62, 0xd2, 0xf7,
	0xe1, 0x63, 0x1f, 0x5e, 0x04, 0xce, 0x65, 0x57, 0x3f, 0x33, 0x98, 0xed, 0xbe, 0xc6, 0xcd, 0xf4,
	0x5a, 0xf1, 0xa1, 0xb5, 0xbb, 0x85, 0x8b, 0xc0, 0xf9, 0xbe, 0xa7, 0x30, 0x8f, 0x96, 0x5e, 0x8b,
	0x36, 0x16, 0x8e, 0x73, 0x97, 0x8e, 0x73, 0xff, 0xaf, 0xbb, 0x01, 0xa5, 0x15, 0xf6, 0x47, 0xe8,
	0x98, 0xb0, 0xd3, 0xcc, 0x70, 0xed, 0x7f, 0x2a, 0xdf, 0x29, 0x6f, 0x12, 0x7e, 0x73, 0xf4, 0x79,
	0xde, 0xa9, 0x16, 0x3b, 0x43, 0xfa, 0x9b, 0x68, 0xc9, 0x5c, 0x4f, 0xfc, 0xf7, 0xf1, 0xf2, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0xe4, 0xde, 0xe1, 0x39, 0x03, 0x00, 0x00,
}
