// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkoutinternal.proto

package localservices

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckoutValidationRequest struct {
	BusinessType         string      `protobuf:"bytes,1,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	CartInfo             []*CartInfo `protobuf:"bytes,2,rep,name=cart_info,json=cartInfo,proto3" json:"cart_info,omitempty"`
	Metadata             string      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CheckoutValidationRequest) Reset()         { *m = CheckoutValidationRequest{} }
func (m *CheckoutValidationRequest) String() string { return proto.CompactTextString(m) }
func (*CheckoutValidationRequest) ProtoMessage()    {}
func (*CheckoutValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_50510bfc2501afb7, []int{0}
}
func (m *CheckoutValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutValidationRequest.Unmarshal(m, b)
}
func (m *CheckoutValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutValidationRequest.Marshal(b, m, deterministic)
}
func (dst *CheckoutValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutValidationRequest.Merge(dst, src)
}
func (m *CheckoutValidationRequest) XXX_Size() int {
	return xxx_messageInfo_CheckoutValidationRequest.Size(m)
}
func (m *CheckoutValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutValidationRequest proto.InternalMessageInfo

func (m *CheckoutValidationRequest) GetBusinessType() string {
	if m != nil {
		return m.BusinessType
	}
	return ""
}

func (m *CheckoutValidationRequest) GetCartInfo() []*CartInfo {
	if m != nil {
		return m.CartInfo
	}
	return nil
}

func (m *CheckoutValidationRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type CheckoutValidationResponse struct {
	Order                *OrderCI `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Metadata             string   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutValidationResponse) Reset()         { *m = CheckoutValidationResponse{} }
func (m *CheckoutValidationResponse) String() string { return proto.CompactTextString(m) }
func (*CheckoutValidationResponse) ProtoMessage()    {}
func (*CheckoutValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_50510bfc2501afb7, []int{1}
}
func (m *CheckoutValidationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutValidationResponse.Unmarshal(m, b)
}
func (m *CheckoutValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutValidationResponse.Marshal(b, m, deterministic)
}
func (dst *CheckoutValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutValidationResponse.Merge(dst, src)
}
func (m *CheckoutValidationResponse) XXX_Size() int {
	return xxx_messageInfo_CheckoutValidationResponse.Size(m)
}
func (m *CheckoutValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutValidationResponse proto.InternalMessageInfo

func (m *CheckoutValidationResponse) GetOrder() *OrderCI {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *CheckoutValidationResponse) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type CartInfo struct {
	Quantity             int64         `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	DataType             string        `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	RequestField         *RequestField `protobuf:"bytes,3,opt,name=request_field,json=requestField,proto3" json:"request_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CartInfo) Reset()         { *m = CartInfo{} }
func (m *CartInfo) String() string { return proto.CompactTextString(m) }
func (*CartInfo) ProtoMessage()    {}
func (*CartInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_50510bfc2501afb7, []int{2}
}
func (m *CartInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartInfo.Unmarshal(m, b)
}
func (m *CartInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartInfo.Marshal(b, m, deterministic)
}
func (dst *CartInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartInfo.Merge(dst, src)
}
func (m *CartInfo) XXX_Size() int {
	return xxx_messageInfo_CartInfo.Size(m)
}
func (m *CartInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CartInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CartInfo proto.InternalMessageInfo

func (m *CartInfo) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *CartInfo) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *CartInfo) GetRequestField() *RequestField {
	if m != nil {
		return m.RequestField
	}
	return nil
}

type OrderCI struct {
	Order                int64    `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCI) Reset()         { *m = OrderCI{} }
func (m *OrderCI) String() string { return proto.CompactTextString(m) }
func (*OrderCI) ProtoMessage()    {}
func (*OrderCI) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_50510bfc2501afb7, []int{3}
}
func (m *OrderCI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCI.Unmarshal(m, b)
}
func (m *OrderCI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCI.Marshal(b, m, deterministic)
}
func (dst *OrderCI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCI.Merge(dst, src)
}
func (m *OrderCI) XXX_Size() int {
	return xxx_messageInfo_OrderCI.Size(m)
}
func (m *OrderCI) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCI.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCI proto.InternalMessageInfo

func (m *OrderCI) GetOrder() int64 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *OrderCI) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RequestField struct {
	// Product
	ProductId int64  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price     int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	SpecSet   string `protobuf:"bytes,4,opt,name=spec_set,json=specSet,proto3" json:"spec_set,omitempty"`
	// Shipping
	ShippingId      int64 `protobuf:"varint,5,opt,name=shipping_id,json=shippingId,proto3" json:"shipping_id,omitempty"`
	SpId            int64 `protobuf:"varint,6,opt,name=sp_id,json=spId,proto3" json:"sp_id,omitempty"`
	OriginAddressId int64 `protobuf:"varint,7,opt,name=origin_address_id,json=originAddressId,proto3" json:"origin_address_id,omitempty"`
	DestAddressId   int64 `protobuf:"varint,8,opt,name=dest_address_id,json=destAddressId,proto3" json:"dest_address_id,omitempty"`
	Insurance       int64 `protobuf:"varint,9,opt,name=insurance,proto3" json:"insurance,omitempty"`
	OrderValue      int64 `protobuf:"varint,10,opt,name=order_value,json=orderValue,proto3" json:"order_value,omitempty"`
	// All
	Dimension            string   `protobuf:"bytes,11,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Weight               int64    `protobuf:"varint,12,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestField) Reset()         { *m = RequestField{} }
func (m *RequestField) String() string { return proto.CompactTextString(m) }
func (*RequestField) ProtoMessage()    {}
func (*RequestField) Descriptor() ([]byte, []int) {
	return fileDescriptor_checkoutinternal_50510bfc2501afb7, []int{4}
}
func (m *RequestField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestField.Unmarshal(m, b)
}
func (m *RequestField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestField.Marshal(b, m, deterministic)
}
func (dst *RequestField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestField.Merge(dst, src)
}
func (m *RequestField) XXX_Size() int {
	return xxx_messageInfo_RequestField.Size(m)
}
func (m *RequestField) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestField.DiscardUnknown(m)
}

var xxx_messageInfo_RequestField proto.InternalMessageInfo

func (m *RequestField) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *RequestField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestField) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *RequestField) GetSpecSet() string {
	if m != nil {
		return m.SpecSet
	}
	return ""
}

func (m *RequestField) GetShippingId() int64 {
	if m != nil {
		return m.ShippingId
	}
	return 0
}

func (m *RequestField) GetSpId() int64 {
	if m != nil {
		return m.SpId
	}
	return 0
}

func (m *RequestField) GetOriginAddressId() int64 {
	if m != nil {
		return m.OriginAddressId
	}
	return 0
}

func (m *RequestField) GetDestAddressId() int64 {
	if m != nil {
		return m.DestAddressId
	}
	return 0
}

func (m *RequestField) GetInsurance() int64 {
	if m != nil {
		return m.Insurance
	}
	return 0
}

func (m *RequestField) GetOrderValue() int64 {
	if m != nil {
		return m.OrderValue
	}
	return 0
}

func (m *RequestField) GetDimension() string {
	if m != nil {
		return m.Dimension
	}
	return ""
}

func (m *RequestField) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckoutValidationRequest)(nil), "CheckoutValidationRequest")
	proto.RegisterType((*CheckoutValidationResponse)(nil), "CheckoutValidationResponse")
	proto.RegisterType((*CartInfo)(nil), "CartInfo")
	proto.RegisterType((*OrderCI)(nil), "OrderCI")
	proto.RegisterType((*RequestField)(nil), "RequestField")
}

func init() {
	proto.RegisterFile("checkoutinternal.proto", fileDescriptor_checkoutinternal_50510bfc2501afb7)
}

var fileDescriptor_checkoutinternal_50510bfc2501afb7 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4f, 0x6b, 0x1b, 0x31,
	0x10, 0xc5, 0xb1, 0xd7, 0x7f, 0x76, 0xc7, 0x36, 0xa6, 0x6a, 0x09, 0x9b, 0xf4, 0x5f, 0x70, 0x21,
	0x84, 0x1e, 0x7c, 0x70, 0x0f, 0x3d, 0xb7, 0x86, 0xc2, 0x9e, 0x0a, 0xdb, 0x12, 0x4a, 0x2f, 0x8b,
	0x22, 0x8d, 0x6d, 0xd1, 0xb5, 0xa4, 0x48, 0xda, 0x04, 0xdf, 0xfb, 0x85, 0xfb, 0x0d, 0x8a, 0xa4,
	0xb5, 0xb3, 0x2d, 0xb9, 0xed, 0xfb, 0xcd, 0xe8, 0xcd, 0x9b, 0xc1, 0x86, 0x33, 0xb6, 0x43, 0xf6,
	0x4b, 0x35, 0x4e, 0x48, 0x87, 0x46, 0xd2, 0x7a, 0xa9, 0x8d, 0x72, 0x6a, 0xf1, 0xbb, 0x07, 0xe7,
	0xeb, 0xb6, 0x74, 0x43, 0x6b, 0xc1, 0xa9, 0x13, 0x4a, 0x96, 0x78, 0xd7, 0xa0, 0x75, 0xe4, 0x1d,
	0xcc, 0x6e, 0x1b, 0x2b, 0x24, 0x5a, 0x5b, 0xb9, 0x83, 0xc6, 0xbc, 0x77, 0xd9, 0xbb, 0xce, 0xca,
	0xe9, 0x11, 0x7e, 0x3f, 0x68, 0x24, 0x57, 0x90, 0x31, 0x6a, 0x5c, 0x25, 0xe4, 0x46, 0xe5, 0xfd,
	0xcb, 0xe4, 0x7a, 0xb2, 0xca, 0x96, 0x6b, 0x6a, 0x5c, 0x21, 0x37, 0xaa, 0x4c, 0x59, 0xfb, 0x45,
	0x2e, 0x20, 0xdd, 0xa3, 0xa3, 0x9c, 0x3a, 0x9a, 0x27, 0xc1, 0xe7, 0xa4, 0x17, 0x3f, 0xe0, 0xe2,
	0xa9, 0x14, 0x56, 0x2b, 0x69, 0x91, 0xbc, 0x81, 0xa1, 0x32, 0x1c, 0x4d, 0x18, 0x3f, 0x59, 0xa5,
	0xcb, 0xaf, 0x5e, 0xad, 0x8b, 0x32, 0xe2, 0x7f, 0x9c, 0xfb, 0xff, 0x39, 0x3f, 0x40, 0xba, 0xee,
	0x24, 0xb8, 0x6b, 0xa8, 0x74, 0xc2, 0x1d, 0x82, 0x55, 0x52, 0x9e, 0x34, 0x79, 0x09, 0x99, 0xef,
	0x8f, 0x6b, 0xb6, 0x26, 0x1e, 0x84, 0x15, 0x57, 0x30, 0x33, 0xf1, 0x24, 0xd5, 0x46, 0x60, 0xcd,
	0x43, 0xfe, 0xc9, 0x6a, 0xb6, 0x6c, 0x0f, 0xf5, 0xc5, 0xc3, 0x72, 0x6a, 0x3a, 0x6a, 0xf1, 0x11,
	0xc6, 0x6d, 0x4c, 0xf2, 0xa2, 0x9b, 0x3f, 0x39, 0xa6, 0x3e, 0x83, 0x11, 0xdd, 0xab, 0x46, 0xba,
	0x30, 0x2e, 0x29, 0x5b, 0xb5, 0xf8, 0xd3, 0x87, 0x69, 0xd7, 0x97, 0xbc, 0x06, 0xd0, 0x46, 0xf1,
	0x86, 0xb9, 0x4a, 0xf0, 0xd6, 0x23, 0x6b, 0x49, 0xc1, 0x09, 0x81, 0x81, 0xa4, 0xfb, 0x63, 0xe8,
	0xf0, 0xed, 0x27, 0x6a, 0x23, 0x18, 0x86, 0xa0, 0x49, 0x19, 0x05, 0x39, 0x87, 0xd4, 0x6a, 0x64,
	0x95, 0x45, 0x97, 0x0f, 0x42, 0xf7, 0xd8, 0xeb, 0x6f, 0xe8, 0xc8, 0x5b, 0x98, 0xd8, 0x9d, 0xd0,
	0x5a, 0xc8, 0xad, 0x1f, 0x32, 0x0c, 0xcf, 0xe0, 0x88, 0x0a, 0x4e, 0x9e, 0xc3, 0xd0, 0x6a, 0x5f,
	0x1a, 0x85, 0xd2, 0xc0, 0xea, 0x82, 0x93, 0xf7, 0xf0, 0x4c, 0x19, 0xb1, 0x15, 0xb2, 0xa2, 0x9c,
	0x1b, 0xff, 0x2b, 0x11, 0x3c, 0x1f, 0x87, 0x86, 0x79, 0x2c, 0x7c, 0x8a, 0xbc, 0xe0, 0xe4, 0x0a,
	0xe6, 0xdc, 0x1f, 0xb0, 0xd3, 0x99, 0x86, 0xce, 0x99, 0xc7, 0x8f, 0x7d, 0xaf, 0x20, 0x13, 0xd2,
	0x36, 0x86, 0x4a, 0x86, 0x79, 0x16, 0x97, 0x3d, 0x01, 0x9f, 0x33, 0x5c, 0xaf, 0xba, 0xa7, 0x75,
	0x83, 0x39, 0xc4, 0x9c, 0x01, 0xdd, 0x78, 0xe2, 0x9f, 0x73, 0xb1, 0x47, 0x69, 0x85, 0x92, 0xf9,
	0x24, 0x2c, 0xf9, 0x08, 0xfc, 0xcd, 0x1f, 0x50, 0x6c, 0x77, 0x2e, 0x9f, 0xc6, 0x9b, 0x47, 0xf5,
	0x79, 0xfe, 0x73, 0x56, 0x2b, 0x46, 0x6b, 0x8b, 0xe6, 0x5e, 0x30, 0xb4, 0xb7, 0xa3, 0xf0, 0xf7,
	0xf8, 0xf0, 0x37, 0x00, 0x00, 0xff, 0xff, 0x80, 0x68, 0x16, 0x17, 0x38, 0x03, 0x00, 0x00,
}
