// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package localservices

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Order struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TxInvoice            string       `protobuf:"bytes,2,opt,name=tx_invoice,json=txInvoice,proto3" json:"tx_invoice,omitempty"`
	TxAmount             float64      `protobuf:"fixed64,3,opt,name=tx_amount,json=txAmount,proto3" json:"tx_amount,omitempty"`
	TxStatus             int64        `protobuf:"varint,4,opt,name=tx_status,json=txStatus,proto3" json:"tx_status,omitempty"`
	OrderDetail          *OrderDetail `protobuf:"bytes,5,opt,name=order_detail,json=orderDetail,proto3" json:"order_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_62b8ea271137d6f6, []int{0}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetTxInvoice() string {
	if m != nil {
		return m.TxInvoice
	}
	return ""
}

func (m *Order) GetTxAmount() float64 {
	if m != nil {
		return m.TxAmount
	}
	return 0
}

func (m *Order) GetTxStatus() int64 {
	if m != nil {
		return m.TxStatus
	}
	return 0
}

func (m *Order) GetOrderDetail() *OrderDetail {
	if m != nil {
		return m.OrderDetail
	}
	return nil
}

type OrderDetail struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId              int64                `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	VendorId             int64                `protobuf:"varint,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ProductId            int64                `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderDetailName      string               `protobuf:"bytes,5,opt,name=order_detail_name,json=orderDetailName,proto3" json:"order_detail_name,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderDetail) Reset()         { *m = OrderDetail{} }
func (m *OrderDetail) String() string { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()    {}
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_62b8ea271137d6f6, []int{1}
}
func (m *OrderDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetail.Unmarshal(m, b)
}
func (m *OrderDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetail.Marshal(b, m, deterministic)
}
func (dst *OrderDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetail.Merge(dst, src)
}
func (m *OrderDetail) XXX_Size() int {
	return xxx_messageInfo_OrderDetail.Size(m)
}
func (m *OrderDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetail.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetail proto.InternalMessageInfo

func (m *OrderDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderDetail) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderDetail) GetVendorId() int64 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *OrderDetail) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *OrderDetail) GetOrderDetailName() string {
	if m != nil {
		return m.OrderDetailName
	}
	return ""
}

func (m *OrderDetail) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *OrderDetail) GetUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

type GetOrderRequest struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_62b8ea271137d6f6, []int{2}
}
func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (dst *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(dst, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type GetOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_62b8ea271137d6f6, []int{3}
}
func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (dst *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(dst, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type CreateOrderRequest struct {
	TxInvoice            string              `protobuf:"bytes,1,opt,name=tx_invoice,json=txInvoice,proto3" json:"tx_invoice,omitempty"`
	TxAmount             float64             `protobuf:"fixed64,2,opt,name=tx_amount,json=txAmount,proto3" json:"tx_amount,omitempty"`
	TxStatus             int64               `protobuf:"varint,3,opt,name=tx_status,json=txStatus,proto3" json:"tx_status,omitempty"`
	OrderDetail          *OrderDetailRequest `protobuf:"bytes,4,opt,name=order_detail,json=orderDetail,proto3" json:"order_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_62b8ea271137d6f6, []int{4}
}
func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (dst *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(dst, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetTxInvoice() string {
	if m != nil {
		return m.TxInvoice
	}
	return ""
}

func (m *CreateOrderRequest) GetTxAmount() float64 {
	if m != nil {
		return m.TxAmount
	}
	return 0
}

func (m *CreateOrderRequest) GetTxStatus() int64 {
	if m != nil {
		return m.TxStatus
	}
	return 0
}

func (m *CreateOrderRequest) GetOrderDetail() *OrderDetailRequest {
	if m != nil {
		return m.OrderDetail
	}
	return nil
}

type CreateOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_62b8ea271137d6f6, []int{5}
}
func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (dst *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(dst, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

type UpdateOrderStatusRequest struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TxStatus             int64    `protobuf:"varint,2,opt,name=tx_status,json=txStatus,proto3" json:"tx_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderStatusRequest) Reset()         { *m = UpdateOrderStatusRequest{} }
func (m *UpdateOrderStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderStatusRequest) ProtoMessage()    {}
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_62b8ea271137d6f6, []int{6}
}
func (m *UpdateOrderStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderStatusRequest.Unmarshal(m, b)
}
func (m *UpdateOrderStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderStatusRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateOrderStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderStatusRequest.Merge(dst, src)
}
func (m *UpdateOrderStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderStatusRequest.Size(m)
}
func (m *UpdateOrderStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderStatusRequest proto.InternalMessageInfo

func (m *UpdateOrderStatusRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *UpdateOrderStatusRequest) GetTxStatus() int64 {
	if m != nil {
		return m.TxStatus
	}
	return 0
}

type UpdateOrderStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderStatusResponse) Reset()         { *m = UpdateOrderStatusResponse{} }
func (m *UpdateOrderStatusResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderStatusResponse) ProtoMessage()    {}
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_62b8ea271137d6f6, []int{7}
}
func (m *UpdateOrderStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderStatusResponse.Unmarshal(m, b)
}
func (m *UpdateOrderStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderStatusResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateOrderStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderStatusResponse.Merge(dst, src)
}
func (m *UpdateOrderStatusResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderStatusResponse.Size(m)
}
func (m *UpdateOrderStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderStatusResponse proto.InternalMessageInfo

type OrderDetailRequest struct {
	VendorId             int64    `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ProductId            int64    `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetailRequest) Reset()         { *m = OrderDetailRequest{} }
func (m *OrderDetailRequest) String() string { return proto.CompactTextString(m) }
func (*OrderDetailRequest) ProtoMessage()    {}
func (*OrderDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_62b8ea271137d6f6, []int{8}
}
func (m *OrderDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailRequest.Unmarshal(m, b)
}
func (m *OrderDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailRequest.Marshal(b, m, deterministic)
}
func (dst *OrderDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailRequest.Merge(dst, src)
}
func (m *OrderDetailRequest) XXX_Size() int {
	return xxx_messageInfo_OrderDetailRequest.Size(m)
}
func (m *OrderDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailRequest proto.InternalMessageInfo

func (m *OrderDetailRequest) GetVendorId() int64 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *OrderDetailRequest) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func init() {
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*OrderDetail)(nil), "OrderDetail")
	proto.RegisterType((*GetOrderRequest)(nil), "GetOrderRequest")
	proto.RegisterType((*GetOrderResponse)(nil), "GetOrderResponse")
	proto.RegisterType((*CreateOrderRequest)(nil), "CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "CreateOrderResponse")
	proto.RegisterType((*UpdateOrderStatusRequest)(nil), "UpdateOrderStatusRequest")
	proto.RegisterType((*UpdateOrderStatusResponse)(nil), "UpdateOrderStatusResponse")
	proto.RegisterType((*OrderDetailRequest)(nil), "OrderDetailRequest")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_order_62b8ea271137d6f6) }

var fileDescriptor_order_62b8ea271137d6f6 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xb5, 0x76, 0x93, 0xc6, 0xe3, 0x40, 0x60, 0x2b, 0x24, 0xb7, 0x05, 0x11, 0xf9, 0x14,
	0x21, 0xe4, 0xa0, 0x22, 0x71, 0xe3, 0xc0, 0x1f, 0x09, 0xe5, 0x02, 0x68, 0x81, 0x0b, 0x17, 0xcb,
	0xf5, 0x2e, 0x95, 0x25, 0xdb, 0x6b, 0xbc, 0xe3, 0xc8, 0x9f, 0x06, 0x89, 0x03, 0xdf, 0x13, 0x79,
	0xd6, 0x55, 0xb3, 0x69, 0x95, 0x1e, 0xe7, 0xcd, 0x8c, 0xf7, 0x37, 0xcf, 0x0f, 0x42, 0xdd, 0x4a,
	0xd5, 0x26, 0x4d, 0xab, 0x51, 0x9f, 0x3d, 0xbf, 0xd2, 0xfa, 0xaa, 0x54, 0x6b, 0xaa, 0x2e, 0xbb,
	0x5f, 0x6b, 0x2c, 0x2a, 0x65, 0x30, 0xab, 0x1a, 0x3b, 0x10, 0xff, 0x65, 0x30, 0xf9, 0x32, 0x2c,
	0xf0, 0x87, 0xe0, 0x15, 0x32, 0x62, 0x4b, 0xb6, 0xf2, 0x85, 0x57, 0x48, 0xfe, 0x0c, 0x00, 0xfb,
	0xb4, 0xa8, 0xb7, 0xba, 0xc8, 0x55, 0xe4, 0x2d, 0xd9, 0x2a, 0x10, 0x01, 0xf6, 0x1b, 0x2b, 0xf0,
	0x73, 0x08, 0xb0, 0x4f, 0xb3, 0x4a, 0x77, 0x35, 0x46, 0xfe, 0x92, 0xad, 0x98, 0x98, 0x61, 0xff,
	0x8e, 0xea, 0xb1, 0x69, 0x30, 0xc3, 0xce, 0x44, 0x47, 0xf4, 0xc9, 0x19, 0xf6, 0xdf, 0xa8, 0xe6,
	0x6b, 0x98, 0x13, 0x62, 0x2a, 0x15, 0x66, 0x45, 0x19, 0x4d, 0x96, 0x6c, 0x15, 0x5e, 0xcc, 0x13,
	0xc2, 0xf8, 0x48, 0x9a, 0xb0, 0x47, 0xd8, 0x22, 0xfe, 0xe3, 0x41, 0xb8, 0xd3, 0xbc, 0x45, 0x7a,
	0x0a, 0x33, 0xfb, 0xc1, 0x42, 0x12, 0xa7, 0x2f, 0x8e, 0xa9, 0xde, 0xc8, 0x01, 0x64, 0xab, 0x6a,
	0xa9, 0xa9, 0xe7, 0x5b, 0x10, 0x2b, 0x6c, 0xe8, 0xc2, 0xa6, 0xd5, 0xb2, 0xcb, 0x71, 0xe8, 0x5a,
	0xcc, 0x60, 0x54, 0x36, 0x92, 0xbf, 0x80, 0xc7, 0xbb, 0x9c, 0x69, 0x9d, 0x55, 0x8a, 0x60, 0x03,
	0xb1, 0xd8, 0xc1, 0xfb, 0x9c, 0x55, 0x8a, 0xbf, 0x85, 0x79, 0xde, 0xaa, 0x0c, 0x95, 0x4c, 0x07,
	0x87, 0xa3, 0x29, 0xdd, 0x74, 0x96, 0x58, 0xfb, 0x93, 0x6b, 0xfb, 0x93, 0xef, 0xd7, 0xf6, 0x8b,
	0x70, 0x9c, 0x1f, 0x94, 0x61, 0xbd, 0x6b, 0xe4, 0xcd, 0xfa, 0xf1, 0xfd, 0xeb, 0xe3, 0xfc, 0xa0,
	0xc4, 0x2f, 0x61, 0xf1, 0x49, 0x21, 0x59, 0x24, 0xd4, 0xef, 0x4e, 0x19, 0x74, 0x3c, 0x61, 0x8e,
	0x27, 0xf1, 0x2b, 0x78, 0x74, 0x33, 0x6d, 0x1a, 0x5d, 0x1b, 0xc5, 0x9f, 0xc2, 0x84, 0xda, 0x34,
	0x1b, 0x5e, 0x4c, 0xed, 0xcf, 0x10, 0x56, 0x8c, 0xff, 0x31, 0xe0, 0x1f, 0x08, 0xd7, 0x79, 0xc3,
	0x4d, 0x08, 0x3b, 0x98, 0x10, 0xef, 0x50, 0x42, 0xfc, 0xbd, 0x84, 0xbc, 0xd9, 0x4b, 0xc8, 0x11,
	0x41, 0x9d, 0x38, 0x09, 0xb1, 0x0c, 0x6e, 0x50, 0x9e, 0xc0, 0x89, 0x83, 0x69, 0x8f, 0x8b, 0x05,
	0x44, 0x3f, 0xc8, 0x2d, 0x92, 0xed, 0x1b, 0xf7, 0xfb, 0xe4, 0x22, 0x7a, 0x2e, 0x62, 0x7c, 0x0e,
	0xa7, 0x77, 0x7c, 0x73, 0x7c, 0xf0, 0x2b, 0xf0, 0xdb, 0xa8, 0x6e, 0x16, 0xd9, 0xc1, 0x2c, 0x7a,
	0x7b, 0x59, 0x7c, 0xbf, 0xf8, 0xf9, 0xa0, 0xd4, 0x79, 0x56, 0x1a, 0xd5, 0x6e, 0x8b, 0x5c, 0x99,
	0xcb, 0x29, 0x65, 0xe2, 0xf5, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x87, 0x90, 0x27, 0xee,
	0x03, 0x00, 0x00,
}
