// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product_price.proto

package localservices

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Area struct {
	DistrictId           int64    `protobuf:"varint,1,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	CityId               int64    `protobuf:"varint,2,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	ProvinceId           int64    `protobuf:"varint,3,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Area) Reset()         { *m = Area{} }
func (m *Area) String() string { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()    {}
func (*Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_price_e0f22f69ddbed0ba, []int{0}
}
func (m *Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area.Unmarshal(m, b)
}
func (m *Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area.Marshal(b, m, deterministic)
}
func (dst *Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area.Merge(dst, src)
}
func (m *Area) XXX_Size() int {
	return xxx_messageInfo_Area.Size(m)
}
func (m *Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Area proto.InternalMessageInfo

func (m *Area) GetDistrictId() int64 {
	if m != nil {
		return m.DistrictId
	}
	return 0
}

func (m *Area) GetCityId() int64 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *Area) GetProvinceId() int64 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

type GetProductPriceRequest struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SpecSet              string   `protobuf:"bytes,2,opt,name=spec_set,json=specSet,proto3" json:"spec_set,omitempty"`
	Area                 *Area    `protobuf:"bytes,3,opt,name=area,proto3" json:"area,omitempty"`
	Quantity             int64    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TkpUserId            int64    `protobuf:"varint,5,opt,name=tkp_user_id,json=tkpUserId,proto3" json:"tkp_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductPriceRequest) Reset()         { *m = GetProductPriceRequest{} }
func (m *GetProductPriceRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductPriceRequest) ProtoMessage()    {}
func (*GetProductPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_price_e0f22f69ddbed0ba, []int{1}
}
func (m *GetProductPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductPriceRequest.Unmarshal(m, b)
}
func (m *GetProductPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductPriceRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductPriceRequest.Merge(dst, src)
}
func (m *GetProductPriceRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductPriceRequest.Size(m)
}
func (m *GetProductPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductPriceRequest proto.InternalMessageInfo

func (m *GetProductPriceRequest) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *GetProductPriceRequest) GetSpecSet() string {
	if m != nil {
		return m.SpecSet
	}
	return ""
}

func (m *GetProductPriceRequest) GetArea() *Area {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *GetProductPriceRequest) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *GetProductPriceRequest) GetTkpUserId() int64 {
	if m != nil {
		return m.TkpUserId
	}
	return 0
}

type GetProductPriceResponse struct {
	Prices               []*Price `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductPriceResponse) Reset()         { *m = GetProductPriceResponse{} }
func (m *GetProductPriceResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductPriceResponse) ProtoMessage()    {}
func (*GetProductPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_price_e0f22f69ddbed0ba, []int{2}
}
func (m *GetProductPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductPriceResponse.Unmarshal(m, b)
}
func (m *GetProductPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductPriceResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductPriceResponse.Merge(dst, src)
}
func (m *GetProductPriceResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductPriceResponse.Size(m)
}
func (m *GetProductPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductPriceResponse proto.InternalMessageInfo

func (m *GetProductPriceResponse) GetPrices() []*Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

type Price struct {
	Qty                  int64            `protobuf:"varint,1,opt,name=qty,proto3" json:"qty,omitempty"`
	Unit                 string           `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Partner              *PartnerLocation `protobuf:"bytes,3,opt,name=partner,proto3" json:"partner,omitempty"`
	Options              []*PriceOption   `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	TkpDistrictId        int64            `protobuf:"varint,5,opt,name=tkp_district_id,json=tkpDistrictId,proto3" json:"tkp_district_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_price_e0f22f69ddbed0ba, []int{3}
}
func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (dst *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(dst, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetQty() int64 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *Price) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Price) GetPartner() *PartnerLocation {
	if m != nil {
		return m.Partner
	}
	return nil
}

func (m *Price) GetOptions() []*PriceOption {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Price) GetTkpDistrictId() int64 {
	if m != nil {
		return m.TkpDistrictId
	}
	return 0
}

type PartnerLocation struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 float64  `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartnerLocation) Reset()         { *m = PartnerLocation{} }
func (m *PartnerLocation) String() string { return proto.CompactTextString(m) }
func (*PartnerLocation) ProtoMessage()    {}
func (*PartnerLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_price_e0f22f69ddbed0ba, []int{4}
}
func (m *PartnerLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartnerLocation.Unmarshal(m, b)
}
func (m *PartnerLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartnerLocation.Marshal(b, m, deterministic)
}
func (dst *PartnerLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartnerLocation.Merge(dst, src)
}
func (m *PartnerLocation) XXX_Size() int {
	return xxx_messageInfo_PartnerLocation.Size(m)
}
func (m *PartnerLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_PartnerLocation.DiscardUnknown(m)
}

var xxx_messageInfo_PartnerLocation proto.InternalMessageInfo

func (m *PartnerLocation) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *PartnerLocation) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *PartnerLocation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PartnerLocation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PartnerLocation) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type PriceOption struct {
	ProductionFinishDate string   `protobuf:"bytes,1,opt,name=production_finish_date,json=productionFinishDate,proto3" json:"production_finish_date,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Weight               int64    `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	UnitPrice            int64    `protobuf:"varint,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Price                int64    `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Volume               int64    `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	PriceId              int64    `protobuf:"varint,7,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceOption) Reset()         { *m = PriceOption{} }
func (m *PriceOption) String() string { return proto.CompactTextString(m) }
func (*PriceOption) ProtoMessage()    {}
func (*PriceOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_price_e0f22f69ddbed0ba, []int{5}
}
func (m *PriceOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceOption.Unmarshal(m, b)
}
func (m *PriceOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceOption.Marshal(b, m, deterministic)
}
func (dst *PriceOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceOption.Merge(dst, src)
}
func (m *PriceOption) XXX_Size() int {
	return xxx_messageInfo_PriceOption.Size(m)
}
func (m *PriceOption) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceOption.DiscardUnknown(m)
}

var xxx_messageInfo_PriceOption proto.InternalMessageInfo

func (m *PriceOption) GetProductionFinishDate() string {
	if m != nil {
		return m.ProductionFinishDate
	}
	return ""
}

func (m *PriceOption) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *PriceOption) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *PriceOption) GetUnitPrice() int64 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *PriceOption) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PriceOption) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *PriceOption) GetPriceId() int64 {
	if m != nil {
		return m.PriceId
	}
	return 0
}

func init() {
	proto.RegisterType((*Area)(nil), "Area")
	proto.RegisterType((*GetProductPriceRequest)(nil), "GetProductPriceRequest")
	proto.RegisterType((*GetProductPriceResponse)(nil), "GetProductPriceResponse")
	proto.RegisterType((*Price)(nil), "Price")
	proto.RegisterType((*PartnerLocation)(nil), "PartnerLocation")
	proto.RegisterType((*PriceOption)(nil), "PriceOption")
}

func init() { proto.RegisterFile("product_price.proto", fileDescriptor_product_price_e0f22f69ddbed0ba) }

var fileDescriptor_product_price_e0f22f69ddbed0ba = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9b, 0xc4, 0xae, 0x27, 0x94, 0x56, 0x4b, 0x95, 0xba, 0x48, 0x94, 0x2a, 0x87, 0xaa,
	0xe2, 0x90, 0x43, 0xe1, 0xc2, 0x11, 0x54, 0x81, 0x2c, 0x21, 0x11, 0x19, 0x71, 0xe1, 0x62, 0x2d,
	0xde, 0xa5, 0x5d, 0x25, 0xf5, 0x6e, 0x76, 0xc7, 0x41, 0xf9, 0x49, 0xfc, 0x2a, 0xfe, 0x0a, 0x9a,
	0x59, 0x3b, 0x54, 0x70, 0x9b, 0x37, 0x6f, 0xbc, 0xef, 0xcd, 0x87, 0xe1, 0x99, 0xf3, 0x56, 0x75,
	0x0d, 0xd6, 0xce, 0x9b, 0x46, 0x2f, 0x9c, 0xb7, 0x68, 0xe7, 0x12, 0xc6, 0xef, 0xbc, 0x96, 0xe2,
	0x25, 0x4c, 0x95, 0x09, 0xe8, 0x4d, 0x83, 0xb5, 0x51, 0x45, 0x72, 0x99, 0x5c, 0x8f, 0x2a, 0x18,
	0x52, 0xa5, 0x12, 0x67, 0x90, 0x35, 0x06, 0x77, 0x44, 0x1e, 0x30, 0x99, 0x12, 0x2c, 0x15, 0x7d,
	0xe9, 0xbc, 0xdd, 0x9a, 0xb6, 0xd1, 0x44, 0x8e, 0xe2, 0x97, 0x43, 0xaa, 0x54, 0xf3, 0x5f, 0x09,
	0xcc, 0x3e, 0x6a, 0x5c, 0x46, 0xf5, 0x25, 0x89, 0x57, 0x7a, 0xd3, 0xe9, 0x80, 0xe2, 0x05, 0xc0,
	0x60, 0x6a, 0x2f, 0x9a, 0xf7, 0x99, 0x52, 0x89, 0x73, 0x38, 0x0c, 0x4e, 0x37, 0x75, 0xd0, 0xc8,
	0xa2, 0x79, 0x95, 0x11, 0xfe, 0xa2, 0x51, 0x9c, 0xc3, 0x58, 0x7a, 0x2d, 0x59, 0x6e, 0x7a, 0x33,
	0x59, 0x50, 0x13, 0x15, 0xa7, 0xc4, 0x73, 0x38, 0xdc, 0x74, 0xb2, 0x45, 0x83, 0xbb, 0x62, 0xcc,
	0x4f, 0xee, 0xb1, 0xb8, 0x80, 0x29, 0xae, 0x5c, 0xdd, 0x05, 0xed, 0x49, 0x71, 0x12, 0x15, 0x71,
	0xe5, 0xbe, 0x06, 0xed, 0x4b, 0x35, 0x7f, 0x0b, 0x67, 0xff, 0x59, 0x0d, 0xce, 0xb6, 0x41, 0x8b,
	0x0b, 0x48, 0x79, 0x70, 0xa1, 0x48, 0x2e, 0x47, 0xd7, 0xd3, 0x9b, 0x74, 0x11, 0xf9, 0x3e, 0x4b,
	0x6d, 0x4e, 0x38, 0x23, 0x4e, 0x60, 0xb4, 0xc1, 0x5d, 0xdf, 0x0e, 0x85, 0x42, 0xc0, 0xb8, 0x6b,
	0xcd, 0xd0, 0x04, 0xc7, 0xe2, 0x15, 0x64, 0x4e, 0x7a, 0x6c, 0xb5, 0xef, 0x9b, 0x38, 0x59, 0x2c,
	0x23, 0xfe, 0x64, 0x1b, 0x89, 0xc6, 0xb6, 0xd5, 0x50, 0x20, 0xae, 0x20, 0xb3, 0x8e, 0x52, 0xa1,
	0x18, 0xb3, 0xf8, 0x93, 0x28, 0xfe, 0xd9, 0xc5, 0xba, 0x9e, 0x14, 0x57, 0x70, 0x4c, 0xed, 0x3d,
	0xde, 0x64, 0x6c, 0xf1, 0x08, 0x57, 0xee, 0x76, 0xbf, 0xcc, 0x79, 0x07, 0xc7, 0xff, 0x68, 0x91,
	0xe9, 0xb5, 0x44, 0x36, 0x9d, 0x54, 0x14, 0x92, 0xe9, 0xb5, 0x6d, 0xef, 0xd8, 0x74, 0x52, 0x71,
	0x2c, 0x9e, 0xc2, 0xc1, 0x7e, 0xc7, 0x07, 0x46, 0x51, 0x4d, 0x2b, 0x1f, 0x34, 0xcf, 0x39, 0xaf,
	0x38, 0x16, 0x05, 0x64, 0x52, 0x29, 0xaf, 0x43, 0x60, 0xf1, 0xbc, 0x1a, 0xe0, 0xfc, 0x77, 0x02,
	0xd3, 0x47, 0xbe, 0xc5, 0x1b, 0x98, 0xf5, 0xcb, 0x36, 0xb6, 0xad, 0x7f, 0x98, 0xd6, 0x84, 0xfb,
	0x5a, 0x49, 0xd4, 0x6c, 0x23, 0xaf, 0x4e, 0xff, 0xb2, 0x1f, 0x98, 0xbc, 0x95, 0xa8, 0x69, 0xbf,
	0xaa, 0xf3, 0xec, 0xba, 0x3f, 0xc5, 0x3d, 0x16, 0x33, 0x48, 0x7f, 0x6a, 0x73, 0x77, 0x8f, 0xbd,
	0xc7, 0x1e, 0xd1, 0xa1, 0xd1, 0xd0, 0xe3, 0xe9, 0xf7, 0x57, 0x91, 0x53, 0x26, 0x6e, 0xec, 0x14,
	0x26, 0x91, 0x89, 0xd3, 0x8a, 0x80, 0x1e, 0xdb, 0xda, 0x75, 0xf7, 0xa0, 0x8b, 0x34, 0x3e, 0x16,
	0x11, 0x9d, 0x25, 0x17, 0xd0, 0x78, 0x33, 0x66, 0x32, 0xc6, 0xa5, 0x7a, 0x7f, 0xfc, 0xed, 0x68,
	0x6d, 0x1b, 0xb9, 0x0e, 0xda, 0x6f, 0xe9, 0x2a, 0xbe, 0xa7, 0xfc, 0x9b, 0xbd, 0xfe, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x85, 0x7f, 0x4a, 0x15, 0x7d, 0x03, 0x00, 0x00,
}
