// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product_spec_map.proto

package localservices

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProductSpecMap struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            int64    `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductSpecId        int64    `protobuf:"varint,3,opt,name=product_spec_id,json=productSpecId,proto3" json:"product_spec_id,omitempty"`
	ProductSpecDetail    string   `protobuf:"bytes,4,opt,name=product_spec_detail,json=productSpecDetail,proto3" json:"product_spec_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductSpecMap) Reset()         { *m = ProductSpecMap{} }
func (m *ProductSpecMap) String() string { return proto.CompactTextString(m) }
func (*ProductSpecMap) ProtoMessage()    {}
func (*ProductSpecMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_map_4e6f2110c464b9ba, []int{0}
}
func (m *ProductSpecMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSpecMap.Unmarshal(m, b)
}
func (m *ProductSpecMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSpecMap.Marshal(b, m, deterministic)
}
func (dst *ProductSpecMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSpecMap.Merge(dst, src)
}
func (m *ProductSpecMap) XXX_Size() int {
	return xxx_messageInfo_ProductSpecMap.Size(m)
}
func (m *ProductSpecMap) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSpecMap.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSpecMap proto.InternalMessageInfo

func (m *ProductSpecMap) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductSpecMap) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *ProductSpecMap) GetProductSpecId() int64 {
	if m != nil {
		return m.ProductSpecId
	}
	return 0
}

func (m *ProductSpecMap) GetProductSpecDetail() string {
	if m != nil {
		return m.ProductSpecDetail
	}
	return ""
}

type CreateProductSpecMapRequest struct {
	ProductSpecMap       *ProductSpecMap `protobuf:"bytes,1,opt,name=product_spec_map,json=productSpecMap,proto3" json:"product_spec_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateProductSpecMapRequest) Reset()         { *m = CreateProductSpecMapRequest{} }
func (m *CreateProductSpecMapRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductSpecMapRequest) ProtoMessage()    {}
func (*CreateProductSpecMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_map_4e6f2110c464b9ba, []int{1}
}
func (m *CreateProductSpecMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductSpecMapRequest.Unmarshal(m, b)
}
func (m *CreateProductSpecMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductSpecMapRequest.Marshal(b, m, deterministic)
}
func (dst *CreateProductSpecMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductSpecMapRequest.Merge(dst, src)
}
func (m *CreateProductSpecMapRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductSpecMapRequest.Size(m)
}
func (m *CreateProductSpecMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductSpecMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductSpecMapRequest proto.InternalMessageInfo

func (m *CreateProductSpecMapRequest) GetProductSpecMap() *ProductSpecMap {
	if m != nil {
		return m.ProductSpecMap
	}
	return nil
}

type CreateProductSpecMapResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductSpecMapResponse) Reset()         { *m = CreateProductSpecMapResponse{} }
func (m *CreateProductSpecMapResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductSpecMapResponse) ProtoMessage()    {}
func (*CreateProductSpecMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_map_4e6f2110c464b9ba, []int{2}
}
func (m *CreateProductSpecMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductSpecMapResponse.Unmarshal(m, b)
}
func (m *CreateProductSpecMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductSpecMapResponse.Marshal(b, m, deterministic)
}
func (dst *CreateProductSpecMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductSpecMapResponse.Merge(dst, src)
}
func (m *CreateProductSpecMapResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductSpecMapResponse.Size(m)
}
func (m *CreateProductSpecMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductSpecMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductSpecMapResponse proto.InternalMessageInfo

type GetProductSpecMapsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductSpecMapsRequest) Reset()         { *m = GetProductSpecMapsRequest{} }
func (m *GetProductSpecMapsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductSpecMapsRequest) ProtoMessage()    {}
func (*GetProductSpecMapsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_map_4e6f2110c464b9ba, []int{3}
}
func (m *GetProductSpecMapsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSpecMapsRequest.Unmarshal(m, b)
}
func (m *GetProductSpecMapsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSpecMapsRequest.Marshal(b, m, deterministic)
}
func (dst *GetProductSpecMapsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSpecMapsRequest.Merge(dst, src)
}
func (m *GetProductSpecMapsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductSpecMapsRequest.Size(m)
}
func (m *GetProductSpecMapsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSpecMapsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSpecMapsRequest proto.InternalMessageInfo

type GetProductSpecMapsResponse struct {
	ProductSpecMap       []*ProductSpecMap `protobuf:"bytes,1,rep,name=product_spec_map,json=productSpecMap,proto3" json:"product_spec_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetProductSpecMapsResponse) Reset()         { *m = GetProductSpecMapsResponse{} }
func (m *GetProductSpecMapsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductSpecMapsResponse) ProtoMessage()    {}
func (*GetProductSpecMapsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_map_4e6f2110c464b9ba, []int{4}
}
func (m *GetProductSpecMapsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductSpecMapsResponse.Unmarshal(m, b)
}
func (m *GetProductSpecMapsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductSpecMapsResponse.Marshal(b, m, deterministic)
}
func (dst *GetProductSpecMapsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductSpecMapsResponse.Merge(dst, src)
}
func (m *GetProductSpecMapsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductSpecMapsResponse.Size(m)
}
func (m *GetProductSpecMapsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductSpecMapsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductSpecMapsResponse proto.InternalMessageInfo

func (m *GetProductSpecMapsResponse) GetProductSpecMap() []*ProductSpecMap {
	if m != nil {
		return m.ProductSpecMap
	}
	return nil
}

type UpdateProductSpecMapRequest struct {
	ProductSpecMap       *ProductSpecMap `protobuf:"bytes,1,opt,name=product_spec_map,json=productSpecMap,proto3" json:"product_spec_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateProductSpecMapRequest) Reset()         { *m = UpdateProductSpecMapRequest{} }
func (m *UpdateProductSpecMapRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductSpecMapRequest) ProtoMessage()    {}
func (*UpdateProductSpecMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_map_4e6f2110c464b9ba, []int{5}
}
func (m *UpdateProductSpecMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductSpecMapRequest.Unmarshal(m, b)
}
func (m *UpdateProductSpecMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductSpecMapRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateProductSpecMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductSpecMapRequest.Merge(dst, src)
}
func (m *UpdateProductSpecMapRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductSpecMapRequest.Size(m)
}
func (m *UpdateProductSpecMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductSpecMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductSpecMapRequest proto.InternalMessageInfo

func (m *UpdateProductSpecMapRequest) GetProductSpecMap() *ProductSpecMap {
	if m != nil {
		return m.ProductSpecMap
	}
	return nil
}

type UpdateProductSpecMapResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductSpecMapResponse) Reset()         { *m = UpdateProductSpecMapResponse{} }
func (m *UpdateProductSpecMapResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductSpecMapResponse) ProtoMessage()    {}
func (*UpdateProductSpecMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_spec_map_4e6f2110c464b9ba, []int{6}
}
func (m *UpdateProductSpecMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductSpecMapResponse.Unmarshal(m, b)
}
func (m *UpdateProductSpecMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductSpecMapResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateProductSpecMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductSpecMapResponse.Merge(dst, src)
}
func (m *UpdateProductSpecMapResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductSpecMapResponse.Size(m)
}
func (m *UpdateProductSpecMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductSpecMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductSpecMapResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProductSpecMap)(nil), "ProductSpecMap")
	proto.RegisterType((*CreateProductSpecMapRequest)(nil), "CreateProductSpecMapRequest")
	proto.RegisterType((*CreateProductSpecMapResponse)(nil), "CreateProductSpecMapResponse")
	proto.RegisterType((*GetProductSpecMapsRequest)(nil), "GetProductSpecMapsRequest")
	proto.RegisterType((*GetProductSpecMapsResponse)(nil), "GetProductSpecMapsResponse")
	proto.RegisterType((*UpdateProductSpecMapRequest)(nil), "UpdateProductSpecMapRequest")
	proto.RegisterType((*UpdateProductSpecMapResponse)(nil), "UpdateProductSpecMapResponse")
}

func init() {
	proto.RegisterFile("product_spec_map.proto", fileDescriptor_product_spec_map_4e6f2110c464b9ba)
}

var fileDescriptor_product_spec_map_4e6f2110c464b9ba = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0x89, 0x2f, 0x2e, 0x48, 0x4d, 0x8e, 0xcf, 0x4d, 0x2c, 0xd0, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0x9a, 0xce, 0xc8, 0xc5, 0x17, 0x00, 0x91, 0x0a, 0x2e, 0x48, 0x4d, 0xf6, 0x4d,
	0x2c, 0x10, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca,
	0x4c, 0x11, 0x92, 0xe5, 0xe2, 0x82, 0x69, 0xce, 0x4c, 0x91, 0x60, 0x02, 0x8b, 0x73, 0x42, 0x45,
	0x3c, 0x53, 0x84, 0xd4, 0xb8, 0xf8, 0x51, 0xcc, 0xce, 0x4c, 0x91, 0x60, 0x06, 0xab, 0xe1, 0x2d,
	0x40, 0x98, 0xeb, 0x99, 0x22, 0xa4, 0xc7, 0x25, 0x8c, 0xa2, 0x2e, 0x25, 0xb5, 0x24, 0x31, 0x33,
	0x47, 0x82, 0x45, 0x81, 0x51, 0x83, 0x33, 0x48, 0x10, 0x49, 0xad, 0x0b, 0x58, 0x42, 0x29, 0x82,
	0x4b, 0xda, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x15, 0xd5, 0x79, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0x96, 0x5c, 0x02, 0xe8, 0x5e, 0x02, 0xbb, 0x99, 0xdb, 0x88, 0x5f, 0x0f, 0x4d, 0x07,
	0x5f, 0x01, 0x0a, 0x5f, 0x49, 0x8e, 0x4b, 0x06, 0xbb, 0xc9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9,
	0x4a, 0xd2, 0x5c, 0x92, 0xee, 0xa9, 0x25, 0xa8, 0x92, 0xc5, 0x50, 0x7b, 0x95, 0xc2, 0xb9, 0xa4,
	0xb0, 0x49, 0x42, 0xb4, 0xe2, 0x70, 0x15, 0x33, 0x31, 0xae, 0x8a, 0xe0, 0x92, 0x0e, 0x2d, 0x48,
	0xa1, 0x91, 0x7f, 0xb1, 0x9b, 0x0c, 0x71, 0xb4, 0x13, 0x7f, 0x14, 0x6f, 0x4e, 0x7e, 0x72, 0x62,
	0x4e, 0x71, 0x6a, 0x51, 0x59, 0x66, 0x72, 0x6a, 0x71, 0x12, 0x1b, 0x38, 0x6d, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x57, 0x52, 0x14, 0x91, 0x35, 0x02, 0x00, 0x00,
}
